# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: types.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

import warnings
from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class ChannelChannelFlag(betterproto2.Enum):
    NONE = 0

    EXPLICIT = 1
    """
    1<<0
    """


class ChannelType(betterproto2.Enum):
    TEXT = 0

    VOICE = 1

    CATEGORY = 2


class CommunityPermission(betterproto2.Enum):
    NO_PERMISSION = 0

    ADMINISTRATOR = 1
    """
    1<<0
    """

    VIEW_CHANNEL = 2
    """
    1<<1
    """

    SEND_MESSAGES = 4
    """
    1<<2
    """

    CONNECT_VOICE = 8
    """
    1<<3
    """

    MODIFY_CHANNEL = 16
    """
    1<<4
    """

    SEND_MEDIA = 32
    """
    1<<5
    """

    DELETE_MESSAGES = 64
    """
    1<<6
    """

    PIN_MESSAGES = 128
    """
    1<<7
    """

    SPEAK_VOICE = 256
    """
    1<<8
    """

    MODIFY_COMMUNITY = 512
    """
    1<<9
    """

    MODIFY_ROLES = 1024
    """
    1<<10
    """

    REMOVE_MEMBERS = 2048
    """
    1<<11
    """

    ADD_REACTIONS = 4096
    """
    1<<12
    """

    MODIFY_LINKED_STICKERS = 8192
    """
    1<<13
    """


class MessageMessageType(betterproto2.Enum):
    UNKNOWN = 0

    CALL = 1

    JOIN = 2

    LEAVE = 3


class NotifPrefs(betterproto2.Enum):
    ALL = 0

    MENTIONS = 1

    NONE = 2

    DEFAULT = 3


class RelationshipStatus(betterproto2.Enum):
    INVALID = 0

    FRIEND = 1

    FRIEND_REQUEST_INCOMING = 2

    FRIEND_REQUEST_OUTGOING = 3

    BLOCKED = 4

    SUGGESTED_FRIEND = 5


class UserStatusActivityActivityType(betterproto2.Enum):
    CUSTOM = 0

    PLAYING = 1

    LISTENING = 2

    WATCHING = 3


class UserStatusStatus(betterproto2.Enum):
    ONLINE = 0

    IDLE = 1


@dataclass(eq=False, repr=False)
class Channel(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """

    community_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    type: "ChannelType" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, default_factory=lambda: ChannelType(0)
    )

    position: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)

    parent_id: "int | None" = betterproto2.field(
        6, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Channel>
    """

    flags: "int" = betterproto2.field(7, betterproto2.TYPE_UINT64)

    highlighted_msg_id: "int | None" = betterproto2.field(
        8, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message("osmium.client.types", "Channel", Channel)


@dataclass(eq=False, repr=False)
class ChannelOverride(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    channel_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """

    role_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Role>
    """

    permissions: "PermissionOverrides | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.types", "ChannelOverride", ChannelOverride
)


@dataclass(eq=False, repr=False)
class ChatPhoto(betterproto2.Message):
    file_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<File>
    """

    preview: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)


default_message_pool.register_message("osmium.client.types", "ChatPhoto", ChatPhoto)


@dataclass(eq=False, repr=False)
class Community(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    owner: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    photo: "ChatPhoto | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    permissions: "int" = betterproto2.field(5, betterproto2.TYPE_FIXED64)

    notif_prefs: "NotifPrefs" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: NotifPrefs(0)
    )

    username: "str | None" = betterproto2.field(
        7, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message("osmium.client.types", "Community", Community)


@dataclass(eq=False, repr=False)
class CommunityMember(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    community_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    role_ids: "list[int]" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Role>
    """

    nickname: "str | None" = betterproto2.field(
        4, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message(
    "osmium.client.types", "CommunityMember", CommunityMember
)


@dataclass(eq=False, repr=False)
class CommunityRole(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Role>
    """

    community_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    permissions: "int" = betterproto2.field(4, betterproto2.TYPE_FIXED64)

    priority: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)

    color: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)

    separated: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)

    public: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "osmium.client.types", "CommunityRole", CommunityRole
)


@dataclass(eq=False, repr=False)
class Conversation(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    last_message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    defaults to chat id if no last message (used for sorting)
    @snowflake<Message>
    """

    last_read_message_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    unread_count: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)

    draft: "str | None" = betterproto2.field(6, betterproto2.TYPE_STRING, optional=True)

    permissions: "PermissionOverrides | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )

    notif_prefs: "NotifPrefs" = betterproto2.field(
        8, betterproto2.TYPE_ENUM, default_factory=lambda: NotifPrefs(0)
    )

    unread_mentions_count: "int" = betterproto2.field(9, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "osmium.client.types", "Conversation", Conversation
)


@dataclass(eq=False, repr=False)
class Entrypoint(betterproto2.Message):
    hostname: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    ip_address: "str | None" = betterproto2.field(
        2, betterproto2.TYPE_STRING, optional=True
    )

    port: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)

    region: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)


default_message_pool.register_message("osmium.client.types", "Entrypoint", Entrypoint)


@dataclass(eq=False, repr=False)
class Group(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Chat>
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    owner: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    participant_ids: "list[int]" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<User>
    """


default_message_pool.register_message("osmium.client.types", "Group", Group)


@dataclass(eq=False, repr=False)
class Message(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    author_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    message: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    reply_to: "int | None" = betterproto2.field(
        5, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Message>
    """

    media: "list[_media__.MessageMedia]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, repeated=True
    )

    entities: "list[MessageEntity]" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, repeated=True
    )

    edited_at: "int | None" = betterproto2.field(
        8, betterproto2.TYPE_UINT64, optional=True
    )

    type: "MessageMessageType | None" = betterproto2.field(
        9, betterproto2.TYPE_ENUM, optional=True
    )

    forward: "MessageMessageForwardInfo | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.types", "Message", Message)


@dataclass(eq=False, repr=False)
class MessageMessageForwardInfo(betterproto2.Message):
    pass


default_message_pool.register_message(
    "osmium.client.types", "Message.MessageForwardInfo", MessageMessageForwardInfo
)


@dataclass(eq=False, repr=False)
class MessageEntity(betterproto2.Message):
    """


    Oneofs:
        - entity:
    """

    start_index: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    length: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    bold: "bool | None" = betterproto2.field(
        3, betterproto2.TYPE_BOOL, optional=True, group="entity"
    )

    italic: "bool | None" = betterproto2.field(
        4, betterproto2.TYPE_BOOL, optional=True, group="entity"
    )

    underline: "bool | None" = betterproto2.field(
        5, betterproto2.TYPE_BOOL, optional=True, group="entity"
    )

    strikethrough: "bool | None" = betterproto2.field(
        6, betterproto2.TYPE_BOOL, optional=True, group="entity"
    )

    code: "bool | None" = betterproto2.field(
        7, betterproto2.TYPE_BOOL, optional=True, group="entity"
    )

    url: "bool | None" = betterproto2.field(
        8, betterproto2.TYPE_BOOL, optional=True, group="entity"
    )
    """
    implicit url (when the msg content is the url)
    """

    spoiler: "MessageEntitySpoilerEntity | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True, group="entity"
    )

    pre: "MessageEntityPreEntity | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True, group="entity"
    )
    """
    code block
    """

    text_url: "MessageEntityTextUrlEntity | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="entity"
    )
    """
    masked url
    """

    custom_emoji: "MessageEntityCustomEmojiEntity | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True, group="entity"
    )

    user_mention: "MessageEntityUserMentionEntity | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True, group="entity"
    )
    """
    @ mention of user by id
    """

    username: "bool | None" = betterproto2.field(
        14, betterproto2.TYPE_BOOL, optional=True, group="entity"
    )
    """
    @ mention of user by name
    """


default_message_pool.register_message(
    "osmium.client.types", "MessageEntity", MessageEntity
)


@dataclass(eq=False, repr=False)
class MessageEntityCustomEmojiEntity(betterproto2.Message):
    emoji_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Emoji>
    """


default_message_pool.register_message(
    "osmium.client.types",
    "MessageEntity.CustomEmojiEntity",
    MessageEntityCustomEmojiEntity,
)


@dataclass(eq=False, repr=False)
class MessageEntityPreEntity(betterproto2.Message):
    language: "str | None" = betterproto2.field(
        1, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message(
    "osmium.client.types", "MessageEntity.PreEntity", MessageEntityPreEntity
)


@dataclass(eq=False, repr=False)
class MessageEntitySpoilerEntity(betterproto2.Message):
    pass


default_message_pool.register_message(
    "osmium.client.types", "MessageEntity.SpoilerEntity", MessageEntitySpoilerEntity
)


@dataclass(eq=False, repr=False)
class MessageEntityTextUrlEntity(betterproto2.Message):
    url: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.types", "MessageEntity.TextUrlEntity", MessageEntityTextUrlEntity
)


@dataclass(eq=False, repr=False)
class MessageEntityUserMentionEntity(betterproto2.Message):
    pass


default_message_pool.register_message(
    "osmium.client.types",
    "MessageEntity.UserMentionEntity",
    MessageEntityUserMentionEntity,
)


@dataclass(eq=False, repr=False)
class PermissionOverrides(betterproto2.Message):
    pos: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)

    neg: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)


default_message_pool.register_message(
    "osmium.client.types", "PermissionOverrides", PermissionOverrides
)


@dataclass(eq=False, repr=False)
class Relationship(betterproto2.Message):
    user_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    status: "RelationshipStatus" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: RelationshipStatus(0)
    )


default_message_pool.register_message(
    "osmium.client.types", "Relationship", Relationship
)


@dataclass(eq=False, repr=False)
class User(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    username: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )

    status: "UserStatus | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    photo: "ChatPhoto | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )

    bot: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)

    icon: "int | None" = betterproto2.field(7, betterproto2.TYPE_FIXED64, optional=True)
    """
    @snowflake<Emoji>
    """

    color: "int | None" = betterproto2.field(8, betterproto2.TYPE_UINT32, optional=True)


default_message_pool.register_message("osmium.client.types", "User", User)


@dataclass(eq=False, repr=False)
class UserStatus(betterproto2.Message):
    online: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    status: "UserStatusStatus | None" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, optional=True
    )

    activities: "list[UserStatusActivity]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    def __post_init__(self) -> None:
        super().__post_init__()
        if self.is_set("online"):
            warnings.warn("UserStatus.online is deprecated", DeprecationWarning)


default_message_pool.register_message("osmium.client.types", "UserStatus", UserStatus)


@dataclass(eq=False, repr=False)
class UserStatusActivity(betterproto2.Message):
    title: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    type: "UserStatusActivityActivityType" = betterproto2.field(
        2,
        betterproto2.TYPE_ENUM,
        default_factory=lambda: UserStatusActivityActivityType(0),
    )

    start_time: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)

    end_time: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, optional=True
    )

    state: "str | None" = betterproto2.field(5, betterproto2.TYPE_STRING, optional=True)


default_message_pool.register_message(
    "osmium.client.types", "UserStatus.Activity", UserStatusActivity
)


from .. import media as _media__
from .. import refs as _refs__
