# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: auth.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class InviteType(betterproto2.Enum):
    UNKNOWN = 0

    COMMUNITY = 1

    GROUP = 2

    USER = 3


@dataclass(eq=False, repr=False)
class Authorization(betterproto2.Message):
    token: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    user: "_types__.User | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    session_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Session>
    """


default_message_pool.register_message(
    "osmium.client.auth", "Authorization", Authorization
)


@dataclass(eq=False, repr=False)
class Authorize(betterproto2.Message):
    """
    auth.authorize -> auth.Authorization
    """

    token: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)


default_message_pool.register_message("osmium.client.auth", "Authorize", Authorize)


@dataclass(eq=False, repr=False)
class CreatedInvite(betterproto2.Message):
    """
    response model for invite creates, for all community/chat/user
    """

    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.auth", "CreatedInvite", CreatedInvite
)


@dataclass(eq=False, repr=False)
class GetSessions(betterproto2.Message):
    """
    auth.getSessions -> auth.Sessions
    """

    pass


default_message_pool.register_message("osmium.client.auth", "GetSessions", GetSessions)


@dataclass(eq=False, repr=False)
class InviteList(betterproto2.Message):
    invites: "list[InvitePreview]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.auth", "InviteList", InviteList)


@dataclass(eq=False, repr=False)
class InvitePreview(betterproto2.Message):
    """


    Oneofs:
        - target_info:
    """

    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    creator_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    target_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Keyable>
    """

    target_type: "InviteType" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, default_factory=lambda: InviteType(0)
    )

    expires_at: "int | None" = betterproto2.field(
        5, betterproto2.TYPE_FIXED64, optional=True
    )

    creator: "_types__.User | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True
    )

    community: "_types__.Community | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="target_info"
    )

    chat: "_types__.Group | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True, group="target_info"
    )

    user: "_types__.User | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True, group="target_info"
    )


default_message_pool.register_message(
    "osmium.client.auth", "InvitePreview", InvitePreview
)


@dataclass(eq=False, repr=False)
class LookupInvite(betterproto2.Message):
    """
    auth.LookupInvite -> auth.InvitePreview
    """

    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.auth", "LookupInvite", LookupInvite
)


@dataclass(eq=False, repr=False)
class ResendEmailVerification(betterproto2.Message):
    """
    auth.resendEmailVerification -> ()
    """

    email: "str | None" = betterproto2.field(1, betterproto2.TYPE_STRING, optional=True)


default_message_pool.register_message(
    "osmium.client.auth", "ResendEmailVerification", ResendEmailVerification
)


@dataclass(eq=False, repr=False)
class ResetPassword(betterproto2.Message):
    """
    auth.resetPassword -> ()
    """

    email: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    confirm: "ResetPasswordResetPasswordConfirm | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.auth", "ResetPassword", ResetPassword
)


@dataclass(eq=False, repr=False)
class ResetPasswordResetPasswordConfirm(betterproto2.Message):
    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    new_password: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.auth",
    "ResetPassword.ResetPasswordConfirm",
    ResetPasswordResetPasswordConfirm,
)


@dataclass(eq=False, repr=False)
class RevokeSessions(betterproto2.Message):
    """
    auth.revokeSessions -> ()
    """

    session_ids: "list[int]" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Session>
    """


default_message_pool.register_message(
    "osmium.client.auth", "RevokeSessions", RevokeSessions
)


@dataclass(eq=False, repr=False)
class Session(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Session>
    """

    client_id: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    device_type: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    device_version: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    app_name: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)

    app_version: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)

    last_active: "int" = betterproto2.field(7, betterproto2.TYPE_FIXED64)

    country: "str | None" = betterproto2.field(
        8, betterproto2.TYPE_STRING, optional=True
    )

    region: "str | None" = betterproto2.field(
        9, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message("osmium.client.auth", "Session", Session)


@dataclass(eq=False, repr=False)
class Sessions(betterproto2.Message):
    sessions: "list[Session]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    current: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Session>
    """


default_message_pool.register_message("osmium.client.auth", "Sessions", Sessions)


@dataclass(eq=False, repr=False)
class SignIn(betterproto2.Message):
    """
    auth.signIn -> auth.Authorization
    """

    email: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    password: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    totp: "str | None" = betterproto2.field(3, betterproto2.TYPE_STRING, optional=True)


default_message_pool.register_message("osmium.client.auth", "SignIn", SignIn)


@dataclass(eq=False, repr=False)
class SignUp(betterproto2.Message):
    """
    auth.signUp -> auth.Authorization
    """

    email: "str | None" = betterproto2.field(1, betterproto2.TYPE_STRING, optional=True)

    password: "str | None" = betterproto2.field(
        2, betterproto2.TYPE_STRING, optional=True
    )

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message("osmium.client.auth", "SignUp", SignUp)


@dataclass(eq=False, repr=False)
class UseInvite(betterproto2.Message):
    """
    auth.UseInvite -> ()
    """

    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("osmium.client.auth", "UseInvite", UseInvite)


@dataclass(eq=False, repr=False)
class VerifyEmail(betterproto2.Message):
    """
    auth.verifyEmail -> ()
    """

    email: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("osmium.client.auth", "VerifyEmail", VerifyEmail)


from .. import types as _types__
