# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'billing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbilling.proto\x12\x15osmium.client.billing\"P\n\x12RequestPaymentLink\x12\x14\n\x0credirect_url\x18\x01 \x01(\t\x12\x0c\n\x04plan\x18\x02 \x01(\t\x12\x16\n\x0e\x62illing_period\x18\x03 \x01(\t\"\'\n\x0bPaymentLink\x12\x10\n\x03url\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_url\"\x14\n\x12\x43\x61ncelSubscription\"\x11\n\x0fGetSubscription\"\xea\x01\n\x0cSubscription\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x12\n\x05since\x18\x02 \x01(\x06H\x00\x88\x01\x01\x12\x1e\n\x11next_renewal_date\x18\x03 \x01(\x04H\x01\x88\x01\x01\x12\x1d\n\x10last_card_digits\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06method\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08\x65nd_date\x18\x06 \x01(\x04H\x04\x88\x01\x01\x42\x08\n\x06_sinceB\x14\n\x12_next_renewal_dateB\x13\n\x11_last_card_digitsB\t\n\x07_methodB\x0b\n\t_end_dateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'billing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTPAYMENTLINK']._serialized_start=40
  _globals['_REQUESTPAYMENTLINK']._serialized_end=120
  _globals['_PAYMENTLINK']._serialized_start=122
  _globals['_PAYMENTLINK']._serialized_end=161
  _globals['_CANCELSUBSCRIPTION']._serialized_start=163
  _globals['_CANCELSUBSCRIPTION']._serialized_end=183
  _globals['_GETSUBSCRIPTION']._serialized_start=185
  _globals['_GETSUBSCRIPTION']._serialized_end=202
  _globals['_SUBSCRIPTION']._serialized_start=205
  _globals['_SUBSCRIPTION']._serialized_end=439
# @@protoc_insertion_point(module_scope)
