# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: discovery.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscovery.proto\x12\x17osmium.client.discovery\x1a\x0btypes.proto\"I\n\x1aGetDiscoverableCommunities\x12\x12\n\x05\x61\x66ter\x18\x01 \x01(\x06H\x00\x88\x01\x01\x12\r\n\x05limit\x18\x02 \x01(\rB\x08\n\x06_after\"\\\n\x14\x44iscoveryCommunities\x12\x44\n\x08listings\x18\x01 \x03(\x0b\x32\x32.osmium.client.discovery.DiscoveryCommunityListing\"\xcc\x01\n\x19\x44iscoveryCommunityListing\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\x06\x12\x0c\n\x04name\x18\x02 \x01(\t\x12-\n\x05photo\x18\x03 \x01(\x0b\x32\x1e.osmium.client.types.ChatPhoto\x12\x13\n\x0binvite_code\x18\x04 \x01(\t\x12\x19\n\x11short_description\x18\x05 \x01(\t\x12\x18\n\x10long_description\x18\x06 \x01(\t\x12\x12\n\ncategories\x18\x07 \x03(\t\"e\n\x14\x44iscoveryListingInfo\x12\x19\n\x11short_description\x18\x02 \x01(\t\x12\x18\n\x10long_description\x18\x03 \x01(\t\x12\x12\n\ncategories\x18\x04 \x03(\tJ\x04\x08\x01\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDISCOVERABLECOMMUNITIES']._serialized_start=57
  _globals['_GETDISCOVERABLECOMMUNITIES']._serialized_end=130
  _globals['_DISCOVERYCOMMUNITIES']._serialized_start=132
  _globals['_DISCOVERYCOMMUNITIES']._serialized_end=224
  _globals['_DISCOVERYCOMMUNITYLISTING']._serialized_start=227
  _globals['_DISCOVERYCOMMUNITYLISTING']._serialized_end=431
  _globals['_DISCOVERYLISTINGINFO']._serialized_start=433
  _globals['_DISCOVERYLISTINGINFO']._serialized_end=534
# @@protoc_insertion_point(module_scope)
