# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: friends.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'friends.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2
import refs_pb2 as refs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfriends.proto\x12\x15osmium.client.friends\x1a\x0btypes.proto\x1a\nrefs.proto\"\x12\n\x10GetRelationships\"s\n\rRelationships\x12\x38\n\rrelationships\x18\x01 \x03(\x0b\x32!.osmium.client.types.Relationship\x12(\n\x05users\x18\x02 \x03(\x0b\x32\x19.osmium.client.types.User\"\xcb\x01\n\x0bSyncFriends\x12\x18\n\x10platform_user_id\x18\x01 \x01(\t\x12\x1f\n\x17hashed_platform_user_id\x18\x02 \x01(\x0c\x12\x1f\n\x12platform_user_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x19\n\x11\x66riend_ids_hashed\x18\x05 \x03(\x0c\x12\x1c\n\x14\x63ommunity_ids_hashed\x18\x06 \x03(\x0c\x42\x15\n\x13_platform_user_name\"\x8a\x02\n\x12\x43hangeRelationship\x12)\n\x04user\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.UserRef\x12P\n\x06\x63hange\x18\x02 \x01(\x0e\x32@.osmium.client.friends.ChangeRelationship.RelationshipChangeType\"w\n\x16RelationshipChangeType\x12\x0b\n\x07INVALID\x10\x00\x12\x12\n\x0eREQUEST_FRIEND\x10\x01\x12\x11\n\rACCEPT_FRIEND\x10\x02\x12\x11\n\rREMOVE_FRIEND\x10\x03\x12\t\n\x05\x42LOCK\x10\x04\x12\x0b\n\x07UNBLOCK\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'friends_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRELATIONSHIPS']._serialized_start=65
  _globals['_GETRELATIONSHIPS']._serialized_end=83
  _globals['_RELATIONSHIPS']._serialized_start=85
  _globals['_RELATIONSHIPS']._serialized_end=200
  _globals['_SYNCFRIENDS']._serialized_start=203
  _globals['_SYNCFRIENDS']._serialized_end=406
  _globals['_CHANGERELATIONSHIP']._serialized_start=409
  _globals['_CHANGERELATIONSHIP']._serialized_end=675
  _globals['_CHANGERELATIONSHIP_RELATIONSHIPCHANGETYPE']._serialized_start=556
  _globals['_CHANGERELATIONSHIP_RELATIONSHIPCHANGETYPE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
