# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reactions.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'reactions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import refs_pb2 as refs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freactions.proto\x12\x17osmium.client.reactions\x1a\nrefs.proto\"\x87\x01\n\x0b\x41\x64\x64Reaction\x12-\n\x08\x63hat_ref\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.ChatRef\x12\x12\n\nmessage_id\x18\x02 \x01(\x06\x12\x35\n\x05\x65moji\x18\x03 \x01(\x0b\x32&.osmium.client.reactions.ReactionEmoji\"\x8a\x01\n\x0eRemoveReaction\x12-\n\x08\x63hat_ref\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.ChatRef\x12\x12\n\nmessage_id\x18\x02 \x01(\x06\x12\x35\n\x05\x65moji\x18\x03 \x01(\x0b\x32&.osmium.client.reactions.ReactionEmoji\"I\n\rReactionEmoji\x12\x17\n\runicode_emoji\x18\x01 \x01(\tH\x00\x12\x16\n\x0c\x63ustom_emoji\x18\x02 \x01(\x06H\x00\x42\x07\n\x05\x65moji\"n\n\x10MessageReactions\x12\x12\n\nmessage_id\x18\x01 \x01(\x06\x12\x46\n\x0freaction_fields\x18\x02 \x03(\x0b\x32-.osmium.client.reactions.MessageReactionField\"\x82\x01\n\x14MessageReactionField\x12\x35\n\x05\x65moji\x18\x01 \x01(\x0b\x32&.osmium.client.reactions.ReactionEmoji\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\n\n\x02me\x18\x03 \x01(\x08\x12\x18\n\x10preview_user_ids\x18\x04 \x03(\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREACTION']._serialized_start=57
  _globals['_ADDREACTION']._serialized_end=192
  _globals['_REMOVEREACTION']._serialized_start=195
  _globals['_REMOVEREACTION']._serialized_end=333
  _globals['_REACTIONEMOJI']._serialized_start=335
  _globals['_REACTIONEMOJI']._serialized_end=408
  _globals['_MESSAGEREACTIONS']._serialized_start=410
  _globals['_MESSAGEREACTIONS']._serialized_end=520
  _globals['_MESSAGEREACTIONFIELD']._serialized_start=523
  _globals['_MESSAGEREACTIONFIELD']._serialized_end=653
# @@protoc_insertion_point(module_scope)
