# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: refs.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'refs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrefs.proto\x12\x12osmium.client.refs\"\xcc\x01\n\x07\x43hatRef\x12+\n\x04user\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.UserRefH\x00\x12\x31\n\x07\x63hannel\x18\x02 \x01(\x0b\x32\x1e.osmium.client.refs.ChannelRefH\x00\x12-\n\x05group\x18\x03 \x01(\x0b\x32\x1c.osmium.client.refs.GroupRefH\x00\x12+\n\x04self\x18\x04 \x01(\x0b\x32\x1b.osmium.client.refs.RefSelfH\x00\x42\x05\n\x03ref\"\x1a\n\x07UserRef\x12\x0f\n\x07user_id\x18\x01 \x01(\x06\"\t\n\x07RefSelf\"6\n\nChannelRef\x12\x14\n\x0c\x63ommunity_id\x18\x01 \x01(\x06\x12\x12\n\nchannel_id\x18\x02 \x01(\x06\"\x1c\n\x08GroupRef\x12\x10\n\x08group_id\x18\x01 \x01(\x06\"\x1c\n\x0eStickerPackRef\x12\n\n\x02id\x18\x01 \x01(\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'refs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREF']._serialized_start=35
  _globals['_CHATREF']._serialized_end=239
  _globals['_USERREF']._serialized_start=241
  _globals['_USERREF']._serialized_end=267
  _globals['_REFSELF']._serialized_start=269
  _globals['_REFSELF']._serialized_end=278
  _globals['_CHANNELREF']._serialized_start=280
  _globals['_CHANNELREF']._serialized_end=334
  _globals['_GROUPREF']._serialized_start=336
  _globals['_GROUPREF']._serialized_end=364
  _globals['_STICKERPACKREF']._serialized_start=366
  _globals['_STICKERPACKREF']._serialized_end=394
# @@protoc_insertion_point(module_scope)
