# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stickers.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'stickers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import media_pb2 as media__pb2
import refs_pb2 as refs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estickers.proto\x12\x16osmium.client.stickers\x1a\x0bmedia.proto\x1a\nrefs.proto\"0\n\x10GetSavedStickers\x12\x12\n\x05since\x18\x01 \x01(\x06H\x00\x88\x01\x01\x42\x08\n\x06_since\"I\n\rSavedStickers\x12\x38\n\x0bsaved_packs\x18\x01 \x03(\x0b\x32#.osmium.client.stickers.StickerPack\"\xb9\x01\n\x0bStickerPack\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x36\n\x04type\x18\x02 \x01(\x0e\x32(.osmium.client.stickers.StickerPack.Type\x12\x0c\n\x04name\x18\x03 \x01(\t\x12+\n\x08stickers\x18\x04 \x03(\x0b\x32\x19.osmium.client.media.File\"+\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07STICKER\x10\x01\x12\t\n\x05\x45MOJI\x10\x02\"&\n\x0fGetStickerFiles\x12\x13\n\x0bsticker_ids\x18\x01 \x03(\x06\"B\n\x0eGetStickerPack\x12\x30\n\x04pack\x18\x01 \x01(\x0b\x32\".osmium.client.refs.StickerPackRef\"\x80\x01\n\x10\x41\x64\x64StickerToPack\x12\x30\n\x04pack\x18\x01 \x01(\x0b\x32\".osmium.client.refs.StickerPackRef\x12:\n\x07sticker\x18\x02 \x01(\x0b\x32).osmium.client.media.MediaRefUploadedFile\"]\n\x15RemoveStickerFromPack\x12\x30\n\x04pack\x18\x01 \x01(\x0b\x32\".osmium.client.refs.StickerPackRef\x12\x12\n\nsticker_id\x18\x02 \x01(\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stickers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSAVEDSTICKERS']._serialized_start=67
  _globals['_GETSAVEDSTICKERS']._serialized_end=115
  _globals['_SAVEDSTICKERS']._serialized_start=117
  _globals['_SAVEDSTICKERS']._serialized_end=190
  _globals['_STICKERPACK']._serialized_start=193
  _globals['_STICKERPACK']._serialized_end=378
  _globals['_STICKERPACK_TYPE']._serialized_start=335
  _globals['_STICKERPACK_TYPE']._serialized_end=378
  _globals['_GETSTICKERFILES']._serialized_start=380
  _globals['_GETSTICKERFILES']._serialized_end=418
  _globals['_GETSTICKERPACK']._serialized_start=420
  _globals['_GETSTICKERPACK']._serialized_end=486
  _globals['_ADDSTICKERTOPACK']._serialized_start=489
  _globals['_ADDSTICKERTOPACK']._serialized_end=617
  _globals['_REMOVESTICKERFROMPACK']._serialized_start=619
  _globals['_REMOVESTICKERFROMPACK']._serialized_end=712
# @@protoc_insertion_point(module_scope)
