# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import refs_pb2 as refs__pb2
import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x13osmium.client.users\x1a\nrefs.proto\x1a\x0btypes.proto\"6\n\nGetProfile\x12(\n\x03ref\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.UserRef\"n\n\x07Profile\x12(\n\x03ref\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.UserRef\x12\x0b\n\x03\x62io\x18\x02 \x01(\t\x12\x1a\n\rpremium_since\x18\x03 \x01(\x06H\x00\x88\x01\x01\x42\x10\n\x0e_premium_since\"\"\n\x0eLookupUsername\x12\x10\n\x08username\x18\x01 \x01(\t\"6\n\x0bUserDetails\x12\'\n\x04user\x18\x01 \x01(\x0b\x32\x19.osmium.client.types.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROFILE']._serialized_start=61
  _globals['_GETPROFILE']._serialized_end=115
  _globals['_PROFILE']._serialized_start=117
  _globals['_PROFILE']._serialized_end=227
  _globals['_LOOKUPUSERNAME']._serialized_start=229
  _globals['_LOOKUPUSERNAME']._serialized_end=263
  _globals['_USERDETAILS']._serialized_start=265
  _globals['_USERDETAILS']._serialized_end=319
# @@protoc_insertion_point(module_scope)
