# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import refs_pb2 as refs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoice.proto\x12\x13osmium.client.voice\x1a\nrefs.proto\"k\n\x08RoomInfo\x12\x0f\n\x07room_id\x18\x01 \x01(\x06\x12-\n\x08\x63hat_ref\x18\x02 \x01(\x0b\x32\x1b.osmium.client.refs.ChatRef\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"\x9b\x01\n\x0fRoomParticipant\x12\x0f\n\x07room_id\x18\x01 \x01(\x06\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x06\x12\r\n\x05muted\x18\x04 \x01(\x08\x12\x10\n\x08\x64\x65\x61\x66\x65ned\x18\x05 \x01(\x08\x12\x17\n\x0fvideo_available\x18\x07 \x01(\x08\x12\x18\n\x10screen_available\x18\x08 \x01(\x08\"<\n\x0bRequestRoom\x12-\n\x08\x63hat_ref\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.ChatRef\"o\n\x0fUpdateRoomState\x12-\n\x08\x63hat_ref\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.ChatRef\x12-\n\x05state\x18\x02 \x01(\x0b\x32\x1e.osmium.client.voice.RoomState\"X\n\tRoomState\x12\x0f\n\x07room_id\x18\x02 \x01(\x06\x12:\n\x0cparticipants\x18\x03 \x03(\x0b\x32$.osmium.client.voice.RoomParticipant\"\x81\x01\n\x15UpdateRoomParticipant\x12-\n\x08\x63hat_ref\x18\x01 \x01(\x0b\x32\x1b.osmium.client.refs.ChatRef\x12\x39\n\x0bparticipant\x18\x02 \x01(\x0b\x32$.osmium.client.voice.RoomParticipantb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOMINFO']._serialized_start=48
  _globals['_ROOMINFO']._serialized_end=155
  _globals['_ROOMPARTICIPANT']._serialized_start=158
  _globals['_ROOMPARTICIPANT']._serialized_end=313
  _globals['_REQUESTROOM']._serialized_start=315
  _globals['_REQUESTROOM']._serialized_end=375
  _globals['_UPDATEROOMSTATE']._serialized_start=377
  _globals['_UPDATEROOMSTATE']._serialized_end=488
  _globals['_ROOMSTATE']._serialized_start=490
  _globals['_ROOMSTATE']._serialized_end=578
  _globals['_UPDATEROOMPARTICIPANT']._serialized_start=581
  _globals['_UPDATEROOMPARTICIPANT']._serialized_end=710
# @@protoc_insertion_point(module_scope)
