# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: stickers.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class StickerPackType(betterproto2.Enum):
    UNKNOWN = 0

    STICKER = 1

    EMOJI = 2


@dataclass(eq=False, repr=False)
class AddStickerToPack(betterproto2.Message):
    """
    stickers.addStickerToPack -> ()
    """

    pack: "_refs__.StickerPackRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    sticker: "_media__.MediaRefUploadedFile | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.stickers", "AddStickerToPack", AddStickerToPack
)


@dataclass(eq=False, repr=False)
class GetSavedStickers(betterproto2.Message):
    """
    media.getSavedStickers -> media.SavedStickers
    """

    since: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, optional=True
    )


default_message_pool.register_message(
    "osmium.client.stickers", "GetSavedStickers", GetSavedStickers
)


@dataclass(eq=False, repr=False)
class GetStickerFiles(betterproto2.Message):
    """
    stickers.getStickerFiles -> media.Files
    """

    sticker_ids: "list[int]" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Sticker>
    """


default_message_pool.register_message(
    "osmium.client.stickers", "GetStickerFiles", GetStickerFiles
)


@dataclass(eq=False, repr=False)
class GetStickerPack(betterproto2.Message):
    """
    stickers.getStickerPack -> stickers.StickerPack
    """

    pack: "_refs__.StickerPackRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.stickers", "GetStickerPack", GetStickerPack
)


@dataclass(eq=False, repr=False)
class RemoveStickerFromPack(betterproto2.Message):
    """
    stickers.removeStickerFromPack -> ()
    """

    pack: "_refs__.StickerPackRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    sticker_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Sticker>
    """


default_message_pool.register_message(
    "osmium.client.stickers", "RemoveStickerFromPack", RemoveStickerFromPack
)


@dataclass(eq=False, repr=False)
class SavedStickers(betterproto2.Message):
    saved_packs: "list[StickerPack]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.stickers", "SavedStickers", SavedStickers
)


@dataclass(eq=False, repr=False)
class StickerPack(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<StickerPack>
    """

    type: "StickerPackType" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: StickerPackType(0)
    )

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    stickers: "list[_media__.File]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.stickers", "StickerPack", StickerPack
)


from .. import media as _media__
from .. import refs as _refs__
