# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: settings.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class RegisterPushSubscriptionPushEncryptionScheme(betterproto2.Enum):
    PUSH_ENCRYPTION_UNKNOWN = 0

    P256_HKDF_SHA256_AES256GCM_V1 = 1


class RegisterPushSubscriptionPushType(betterproto2.Enum):
    UNKNOWN = 0

    WEB = 1

    IOS = 2

    ANDROID_FCM = 3


@dataclass(eq=False, repr=False)
class Account(betterproto2.Message):
    email: "str | None" = betterproto2.field(1, betterproto2.TYPE_STRING, optional=True)

    confirmed: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    has_password: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    totp_enabled: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    pending_delete: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message("osmium.client.settings", "Account", Account)


@dataclass(eq=False, repr=False)
class BackupCode(betterproto2.Message):
    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    used: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "osmium.client.settings", "BackupCode", BackupCode
)


@dataclass(eq=False, repr=False)
class ChangeEmail(betterproto2.Message):
    """
    settings.changeEmail -> ()
    """

    new_email: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.settings", "ChangeEmail", ChangeEmail
)


@dataclass(eq=False, repr=False)
class ChangeNotificationPreferences(betterproto2.Message):
    """
    settings.changeNotificationPreferences -> ()

    Oneofs:
        - scope:
    """

    prefs: "_types__.NotifPrefs" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: _types__.NotifPrefs(0)
    )

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="scope"
    )
    """
    For channel or DM chat
    """

    community_id: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, optional=True, group="scope"
    )
    """
    @snowflake<Community>

    For community-level default
    """


default_message_pool.register_message(
    "osmium.client.settings",
    "ChangeNotificationPreferences",
    ChangeNotificationPreferences,
)


@dataclass(eq=False, repr=False)
class ChangePassword(betterproto2.Message):
    """
    settings.changePassword -> ()
    """

    current_password: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    new_password: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    revoke_sessions: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    Revoke all other sessions after password change
    """


default_message_pool.register_message(
    "osmium.client.settings", "ChangePassword", ChangePassword
)


@dataclass(eq=False, repr=False)
class ChangeStatus(betterproto2.Message):
    """
    settings.changeStatus -> ()
    """

    status: "_types__.UserStatusStatus" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: _types__.UserStatusStatus(0)
    )

    activities: "list[_types__.UserStatusActivity]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.settings", "ChangeStatus", ChangeStatus
)


@dataclass(eq=False, repr=False)
class DeleteAccount(betterproto2.Message):
    """
    settings.deleteAccount -> ()
    """

    cancel: "bool | None" = betterproto2.field(1, betterproto2.TYPE_BOOL, optional=True)


default_message_pool.register_message(
    "osmium.client.settings", "DeleteAccount", DeleteAccount
)


@dataclass(eq=False, repr=False)
class EditProfile(betterproto2.Message):
    """
    settings.editProfile -> ()
    """

    name: "str | None" = betterproto2.field(1, betterproto2.TYPE_STRING, optional=True)

    username: "str | None" = betterproto2.field(
        2, betterproto2.TYPE_STRING, optional=True
    )

    bio: "str | None" = betterproto2.field(3, betterproto2.TYPE_STRING, optional=True)

    icon: "int | None" = betterproto2.field(4, betterproto2.TYPE_FIXED64, optional=True)
    """
    @snowflake<Emoji>
    """

    color: "int | None" = betterproto2.field(5, betterproto2.TYPE_UINT32, optional=True)


default_message_pool.register_message(
    "osmium.client.settings", "EditProfile", EditProfile
)


@dataclass(eq=False, repr=False)
class EditProfilePhoto(betterproto2.Message):
    """
    settings.editProfilePhoto -> ()
    """

    file: "_media__.UploadedFileRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.settings", "EditProfilePhoto", EditProfilePhoto
)


@dataclass(eq=False, repr=False)
class EditUserSettings(betterproto2.Message):
    """
    settings.editUserSettings -> settings.UserSettings
    """

    settings: "UserSettings | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.settings", "EditUserSettings", EditUserSettings
)


@dataclass(eq=False, repr=False)
class GetAccount(betterproto2.Message):
    """
    settings.getAccount -> settings.Account
    """

    pass


default_message_pool.register_message(
    "osmium.client.settings", "GetAccount", GetAccount
)


@dataclass(eq=False, repr=False)
class RegisterPushSubscription(betterproto2.Message):
    """
    settings.registerPushSubscription -> ()

    Oneofs:
        - subscription:
    """

    web: "RegisterPushSubscriptionWebPush | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="subscription"
    )

    push: "RegisterPushSubscriptionPush | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="subscription"
    )


default_message_pool.register_message(
    "osmium.client.settings", "RegisterPushSubscription", RegisterPushSubscription
)


@dataclass(eq=False, repr=False)
class RegisterPushSubscriptionPush(betterproto2.Message):
    type: "RegisterPushSubscriptionPushType" = betterproto2.field(
        1,
        betterproto2.TYPE_ENUM,
        default_factory=lambda: RegisterPushSubscriptionPushType(0),
    )

    token: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    encryption_public_key: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )

    encryption_auth_secret: "str | None" = betterproto2.field(
        4, betterproto2.TYPE_STRING, optional=True
    )

    encryption_key_id: "str | None" = betterproto2.field(
        5, betterproto2.TYPE_STRING, optional=True
    )

    encryption_scheme: "RegisterPushSubscriptionPushEncryptionScheme" = (
        betterproto2.field(
            6,
            betterproto2.TYPE_ENUM,
            default_factory=lambda: RegisterPushSubscriptionPushEncryptionScheme(0),
        )
    )


default_message_pool.register_message(
    "osmium.client.settings",
    "RegisterPushSubscription.Push",
    RegisterPushSubscriptionPush,
)


@dataclass(eq=False, repr=False)
class RegisterPushSubscriptionWebPush(betterproto2.Message):
    endpoint: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    p256dh: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    auth: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.settings",
    "RegisterPushSubscription.WebPush",
    RegisterPushSubscriptionWebPush,
)


@dataclass(eq=False, repr=False)
class RequestTakeout(betterproto2.Message):
    """
    settings.requestTakeout -> ()
    """

    pass


default_message_pool.register_message(
    "osmium.client.settings", "RequestTakeout", RequestTakeout
)


@dataclass(eq=False, repr=False)
class SetupTotp(betterproto2.Message):
    """
    settings.setupTotp -> settings.Totp
    """

    enabled: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    code: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True)


default_message_pool.register_message("osmium.client.settings", "SetupTotp", SetupTotp)


@dataclass(eq=False, repr=False)
class Totp(betterproto2.Message):
    enabled: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    url: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True)

    backup_codes: "list[BackupCode]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.settings", "Totp", Totp)


@dataclass(eq=False, repr=False)
class UnregisterPushSubscription(betterproto2.Message):
    """
    settings.unregisterPushSubscription -> ()
    """

    pass


default_message_pool.register_message(
    "osmium.client.settings", "UnregisterPushSubscription", UnregisterPushSubscription
)


@dataclass(eq=False, repr=False)
class UserSettings(betterproto2.Message):
    community_order: "UserSettingsCommunityOrder | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.settings", "UserSettings", UserSettings
)


@dataclass(eq=False, repr=False)
class UserSettingsCommunityOrder(betterproto2.Message):
    community_ids: "list[int]" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.settings", "UserSettings.CommunityOrder", UserSettingsCommunityOrder
)


from .. import media as _media__
from .. import refs as _refs__
from .. import types as _types__
