# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: media.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class DownloadFilePart(betterproto2.Message):
    """
    media.downloadFilePart -> media.FilePart
    """

    file_ref: "FileRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    offset: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)

    length: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "osmium.client.media", "DownloadFilePart", DownloadFilePart
)


@dataclass(eq=False, repr=False)
class File(betterproto2.Message):
    file_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<File>
    """

    region: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    size: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)

    mimetype: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    filename: "str | None" = betterproto2.field(
        5, betterproto2.TYPE_STRING, optional=True
    )

    metadata: "FileMetadata | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.media", "File", File)


@dataclass(eq=False, repr=False)
class FileMetadata(betterproto2.Message):
    """
    File metadata, used to store information about the file, included with media.

    Oneofs:
        - metadata:
    """

    image: "FileMetadataMetadataImage | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="metadata"
    )

    video: "FileMetadataMetadataVideo | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="metadata"
    )

    audio: "FileMetadataMetadataAudio | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="metadata"
    )

    file: "FileMetadataMetadataFile | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="metadata"
    )

    custom_emoji: "FileMetadataMetadataCustomEmoji | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="metadata"
    )


default_message_pool.register_message(
    "osmium.client.media", "FileMetadata", FileMetadata
)


@dataclass(eq=False, repr=False)
class FileMetadataMetadataAudio(betterproto2.Message):
    duration: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    in seconds
    """


default_message_pool.register_message(
    "osmium.client.media", "FileMetadata.MetadataAudio", FileMetadataMetadataAudio
)


@dataclass(eq=False, repr=False)
class FileMetadataMetadataCustomEmoji(betterproto2.Message):
    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    emoji: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    pack: "_refs__.StickerPackRef | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.media",
    "FileMetadata.MetadataCustomEmoji",
    FileMetadataMetadataCustomEmoji,
)


@dataclass(eq=False, repr=False)
class FileMetadataMetadataFile(betterproto2.Message):
    pass


default_message_pool.register_message(
    "osmium.client.media", "FileMetadata.MetadataFile", FileMetadataMetadataFile
)


@dataclass(eq=False, repr=False)
class FileMetadataMetadataImage(betterproto2.Message):
    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    preview: "bytes | None" = betterproto2.field(
        3, betterproto2.TYPE_BYTES, optional=True
    )


default_message_pool.register_message(
    "osmium.client.media", "FileMetadata.MetadataImage", FileMetadataMetadataImage
)


@dataclass(eq=False, repr=False)
class FileMetadataMetadataVideo(betterproto2.Message):
    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    duration: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    """
    in seconds
    """


default_message_pool.register_message(
    "osmium.client.media", "FileMetadata.MetadataVideo", FileMetadataMetadataVideo
)


@dataclass(eq=False, repr=False)
class FilePart(betterproto2.Message):
    data: "bytes" = betterproto2.field(3, betterproto2.TYPE_BYTES)


default_message_pool.register_message("osmium.client.media", "FilePart", FilePart)


@dataclass(eq=False, repr=False)
class FileRef(betterproto2.Message):
    """


    Oneofs:
        - ref:
    """

    media_file: "FileRefMediaFileRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )

    chat_photo: "FileRefChatPhotoFileRef | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )


default_message_pool.register_message("osmium.client.media", "FileRef", FileRef)


@dataclass(eq=False, repr=False)
class FileRefChatPhotoFileRef(betterproto2.Message):
    file_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<File>
    """


default_message_pool.register_message(
    "osmium.client.media", "FileRef.ChatPhotoFileRef", FileRefChatPhotoFileRef
)


@dataclass(eq=False, repr=False)
class FileRefMediaFileRef(betterproto2.Message):
    file_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<File>
    """


default_message_pool.register_message(
    "osmium.client.media", "FileRef.MediaFileRef", FileRefMediaFileRef
)


@dataclass(eq=False, repr=False)
class Files(betterproto2.Message):
    files: "list[File]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.media", "Files", Files)


@dataclass(eq=False, repr=False)
class MediaEmbed(betterproto2.Message):
    url: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    title: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True)

    description: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )
    """
    TODO: spoiler, etc
    """


default_message_pool.register_message("osmium.client.media", "MediaEmbed", MediaEmbed)


@dataclass(eq=False, repr=False)
class MediaFile(betterproto2.Message):
    file: "File | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    TODO: spoiler, etc
    """


default_message_pool.register_message("osmium.client.media", "MediaFile", MediaFile)


@dataclass(eq=False, repr=False)
class MediaRef(betterproto2.Message):
    """


    Oneofs:
        - ref:
    """

    uploaded: "MediaRefUploadedFile | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )

    embed: "MediaRefEmbed | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )


default_message_pool.register_message("osmium.client.media", "MediaRef", MediaRef)


@dataclass(eq=False, repr=False)
class MediaRefEmbed(betterproto2.Message):
    url: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.media", "MediaRefEmbed", MediaRefEmbed
)


@dataclass(eq=False, repr=False)
class MediaRefUploadedFile(betterproto2.Message):
    file: "UploadedFileRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    filename: "str | None" = betterproto2.field(
        2, betterproto2.TYPE_STRING, optional=True
    )

    mimetype: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    metadata: "FileMetadata | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.media", "MediaRefUploadedFile", MediaRefUploadedFile
)


@dataclass(eq=False, repr=False)
class MessageMedia(betterproto2.Message):
    """
    Media in messages

    Oneofs:
        - media:
    """

    file: "MediaFile | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="media"
    )

    embed: "MediaEmbed | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="media"
    )


default_message_pool.register_message(
    "osmium.client.media", "MessageMedia", MessageMedia
)


@dataclass(eq=False, repr=False)
class UploadedFileRef(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    part_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "osmium.client.media", "UploadedFileRef", UploadedFileRef
)


@dataclass(eq=False, repr=False)
class UploadFilePart(betterproto2.Message):
    """
    media.uploadFilePart -> ()
    """

    upload_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    """
    The identifier of the uploaded file. Generated by the client.
    """

    part: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    data: "bytes" = betterproto2.field(3, betterproto2.TYPE_BYTES)


default_message_pool.register_message(
    "osmium.client.media", "UploadFilePart", UploadFilePart
)


from .. import refs as _refs__
