# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: users.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class GetProfile(betterproto2.Message):
    """
    users.getProfile -> Profile
    """

    ref: "_refs__.UserRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.users", "GetProfile", GetProfile)


@dataclass(eq=False, repr=False)
class LookupUsername(betterproto2.Message):
    """
    users.lookupUsername -> UserDetails
    """

    username: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.users", "LookupUsername", LookupUsername
)


@dataclass(eq=False, repr=False)
class Profile(betterproto2.Message):
    ref: "_refs__.UserRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    bio: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    premium_since: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, optional=True
    )


default_message_pool.register_message("osmium.client.users", "Profile", Profile)


@dataclass(eq=False, repr=False)
class UserDetails(betterproto2.Message):
    user: "_types__.User | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.users", "UserDetails", UserDetails)


from .. import refs as _refs__
from .. import types as _types__
