# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: chats.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class TypingAction(betterproto2.Enum):
    TYPING = 0

    UPLOAD_IMAGE = 1

    UPLOAD_VIDEO = 2

    UPLOAD_FILE = 3

    RECORDING_AUDIO = 4

    RECORDING_VIDEO = 5


@dataclass(eq=False, repr=False)
class Chat(betterproto2.Message):
    chat: "_types__.Conversation | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message: "_types__.Message | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    users: "list[_types__.User]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    group: "_types__.Group | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    channel: "_types__.Channel | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.chats", "Chat", Chat)


@dataclass(eq=False, repr=False)
class Chats(betterproto2.Message):
    chats: "list[_types__.Conversation]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    users: "list[_types__.User]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    groups: "list[_types__.Group]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    channels: "list[_types__.Channel]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    messages: "list[_types__.Message]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.chats", "Chats", Chats)


@dataclass(eq=False, repr=False)
class CreateChat(betterproto2.Message):
    """
    chats.createChat -> types.Group
    """

    users: "list[_refs__.UserRef]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("osmium.client.chats", "CreateChat", CreateChat)


@dataclass(eq=False, repr=False)
class CreateChatInvite(betterproto2.Message):
    """
    chats.createChatInvite -> auth.CreatedInvite
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    expires_at: "int | None" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, optional=True
    )

    max_uses: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT32, optional=True
    )


default_message_pool.register_message(
    "osmium.client.chats", "CreateChatInvite", CreateChatInvite
)


@dataclass(eq=False, repr=False)
class DeleteChatInvite(betterproto2.Message):
    """
    chats.deleteChatInvite -> ()
    """

    code: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.chats", "DeleteChatInvite", DeleteChatInvite
)


@dataclass(eq=False, repr=False)
class GetChat(betterproto2.Message):
    """
    chats.getChat -> chats.Chat
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.chats", "GetChat", GetChat)


@dataclass(eq=False, repr=False)
class GetChats(betterproto2.Message):
    """
    chats.getChats -> chats.Chats
    """

    limit: "int | None" = betterproto2.field(1, betterproto2.TYPE_UINT32, optional=True)

    max_id: "int | None" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Chat>
    """

    min_id: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Chat>
    """


default_message_pool.register_message("osmium.client.chats", "GetChats", GetChats)


@dataclass(eq=False, repr=False)
class ListChatInvites(betterproto2.Message):
    """
    chats.listChatInvites -> auth.InviteList
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.chats", "ListChatInvites", ListChatInvites
)


@dataclass(eq=False, repr=False)
class MarkChatRead(betterproto2.Message):
    """
    chats.markChatRead -> ()
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    read_amount: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT32, optional=True
    )


default_message_pool.register_message(
    "osmium.client.chats", "MarkChatRead", MarkChatRead
)


@dataclass(eq=False, repr=False)
class RemoveChatMember(betterproto2.Message):
    """
    chats.removeChatMember -> ()
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    user_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """


default_message_pool.register_message(
    "osmium.client.chats", "RemoveChatMember", RemoveChatMember
)


@dataclass(eq=False, repr=False)
class SetTyping(betterproto2.Message):
    """
    chats.setTyping -> ()
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    typing: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    action: "TypingAction | None" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, optional=True
    )


default_message_pool.register_message("osmium.client.chats", "SetTyping", SetTyping)


@dataclass(eq=False, repr=False)
class UpdateChat(betterproto2.Message):
    """
    chats.updateChat -> chats.Chat
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    name: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True)

    highlighted_msg_id: "UpdateChatHighlightedMessage | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    None to not modify, 0 to modify to None, >0 to modify to Some(msg_id)
    """


default_message_pool.register_message("osmium.client.chats", "UpdateChat", UpdateChat)


@dataclass(eq=False, repr=False)
class UpdateChatHighlightedMessage(betterproto2.Message):
    highlighted_msg_id: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.chats", "UpdateChat.HighlightedMessage", UpdateChatHighlightedMessage
)


from .. import refs as _refs__
from .. import types as _types__
