# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: reactions.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class AddReaction(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    emoji: "ReactionEmoji | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.reactions", "AddReaction", AddReaction
)


@dataclass(eq=False, repr=False)
class MessageReactionField(betterproto2.Message):
    emoji: "ReactionEmoji | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    count: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    me: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    preview_user_ids: "list[int]" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<User>
    """


default_message_pool.register_message(
    "osmium.client.reactions", "MessageReactionField", MessageReactionField
)


@dataclass(eq=False, repr=False)
class MessageReactions(betterproto2.Message):
    message_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    reaction_fields: "list[MessageReactionField]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.reactions", "MessageReactions", MessageReactions
)


@dataclass(eq=False, repr=False)
class ReactionEmoji(betterproto2.Message):
    """


    Oneofs:
        - emoji:
    """

    unicode_emoji: "str | None" = betterproto2.field(
        1, betterproto2.TYPE_STRING, optional=True, group="emoji"
    )

    custom_emoji: "int | None" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, optional=True, group="emoji"
    )
    """
    @snowflake<Emoji>
    """


default_message_pool.register_message(
    "osmium.client.reactions", "ReactionEmoji", ReactionEmoji
)


@dataclass(eq=False, repr=False)
class RemoveReaction(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    emoji: "ReactionEmoji | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.reactions", "RemoveReaction", RemoveReaction
)


from .. import refs as _refs__
