# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: friends.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class ChangeRelationshipRelationshipChangeType(betterproto2.Enum):
    INVALID = 0

    REQUEST_FRIEND = 1

    ACCEPT_FRIEND = 2

    REMOVE_FRIEND = 3

    BLOCK = 4

    UNBLOCK = 5


@dataclass(eq=False, repr=False)
class ChangeRelationship(betterproto2.Message):
    """
    friends.changeRelationship -> ()
    """

    user: "_refs__.UserRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    change: "ChangeRelationshipRelationshipChangeType" = betterproto2.field(
        2,
        betterproto2.TYPE_ENUM,
        default_factory=lambda: ChangeRelationshipRelationshipChangeType(0),
    )


default_message_pool.register_message(
    "osmium.client.friends", "ChangeRelationship", ChangeRelationship
)


@dataclass(eq=False, repr=False)
class GetRelationships(betterproto2.Message):
    """
    friends.getRelationships -> Relationships
    """

    pass


default_message_pool.register_message(
    "osmium.client.friends", "GetRelationships", GetRelationships
)


@dataclass(eq=False, repr=False)
class Relationships(betterproto2.Message):
    relationships: "list[_types__.Relationship]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    users: "list[_types__.User]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.friends", "Relationships", Relationships
)


@dataclass(eq=False, repr=False)
class SyncFriends(betterproto2.Message):
    """
    friends.syncFriends -> ()
    """

    platform_user_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    hashed_platform_user_id: "bytes" = betterproto2.field(2, betterproto2.TYPE_BYTES)

    platform_user_name: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )

    platform: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    friend_ids_hashed: "list[bytes]" = betterproto2.field(
        5, betterproto2.TYPE_BYTES, repeated=True
    )

    community_ids_hashed: "list[bytes]" = betterproto2.field(
        6, betterproto2.TYPE_BYTES, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.friends", "SyncFriends", SyncFriends
)


from .. import refs as _refs__
from .. import types as _types__
