# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: voice.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class RequestRoom(betterproto2.Message):
    """
    voice.requestRoom -> RoomInfo
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.voice", "RequestRoom", RequestRoom)


@dataclass(eq=False, repr=False)
class RoomInfo(betterproto2.Message):
    room_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    endpoint: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    token: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)


default_message_pool.register_message("osmium.client.voice", "RoomInfo", RoomInfo)


@dataclass(eq=False, repr=False)
class RoomParticipant(betterproto2.Message):
    room_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake
    """

    session_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    user_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    muted: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    deafened: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    video_available: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)

    screen_available: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "osmium.client.voice", "RoomParticipant", RoomParticipant
)


@dataclass(eq=False, repr=False)
class RoomState(betterproto2.Message):
    room_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake
    """

    participants: "list[RoomParticipant]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.voice", "RoomState", RoomState)


@dataclass(eq=False, repr=False)
class UpdateRoomParticipant(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    participant: "RoomParticipant | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.voice", "UpdateRoomParticipant", UpdateRoomParticipant
)


@dataclass(eq=False, repr=False)
class UpdateRoomState(betterproto2.Message):
    """
    Updates
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    state: "RoomState | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.voice", "UpdateRoomState", UpdateRoomState
)


from .. import refs as _refs__
