# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: core.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class ClientMessage(betterproto2.Message):
    """


    Oneofs:
        - message:
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    auth_sign_in: "_auth__.SignIn | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_sign_up: "_auth__.SignUp | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_send_message: "_messages__.SendMessage | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_get_history: "_messages__.GetHistory | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_create_community: "_communities__.CreateCommunity | None" = (
        betterproto2.field(6, betterproto2.TYPE_MESSAGE, optional=True, group="message")
    )

    communities_get_communities: "_communities__.GetCommunities | None" = (
        betterproto2.field(7, betterproto2.TYPE_MESSAGE, optional=True, group="message")
    )

    communities_create_channel: "_communities__.CreateChannel | None" = (
        betterproto2.field(8, betterproto2.TYPE_MESSAGE, optional=True, group="message")
    )

    communities_get_channels: "_communities__.GetChannels | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    friends_get_relationships: "_friends__.GetRelationships | None" = (
        betterproto2.field(
            10, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    chats_get_chats: "_chats__.GetChats | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    media_upload_file_part: "_media__.UploadFilePart | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    media_download_file_part: "_media__.DownloadFilePart | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    chats_create_chat_invite: "_chats__.CreateChatInvite | None" = betterproto2.field(
        14, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_lookup_invite: "_auth__.LookupInvite | None" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_use_invite: "_auth__.UseInvite | None" = betterproto2.field(
        16, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_delete_message: "_messages__.DeleteMessage | None" = betterproto2.field(
        17, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_get_channel_members: "_communities__.GetChannelMembers | None" = (
        betterproto2.field(
            18, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    core_initialize: "Initialize | None" = betterproto2.field(
        19, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_authorize: "_auth__.Authorize | None" = betterproto2.field(
        20, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    chats_mark_chat_read: "_chats__.MarkChatRead | None" = betterproto2.field(
        21, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_edit_profile_photo: "_settings__.EditProfilePhoto | None" = (
        betterproto2.field(
            22, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    communities_edit_photo: "_communities__.EditPhoto | None" = betterproto2.field(
        23, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_delete_channel: "_communities__.DeleteChannel | None" = (
        betterproto2.field(
            24, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    chats_get_chat: "_chats__.GetChat | None" = betterproto2.field(
        25, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_edit_message: "_messages__.EditMessage | None" = betterproto2.field(
        26, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_get_roles: "_communities__.GetRoles | None" = betterproto2.field(
        27, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    chats_set_typing: "_chats__.SetTyping | None" = betterproto2.field(
        28, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_create_role: "_communities__.CreateRole | None" = betterproto2.field(
        29, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_edit_role: "_communities__.EditRole | None" = betterproto2.field(
        30, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_delete_role: "_communities__.DeleteRole | None" = betterproto2.field(
        31, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_edit_member: "_communities__.EditMember | None" = betterproto2.field(
        32, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_create_channel_override: "_communities__.CreateChannelOverride | None" = betterproto2.field(
        33, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_delete_channel_override: "_communities__.DeleteChannelOverride | None" = betterproto2.field(
        34, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_get_channel_overrides: "_communities__.GetChannelOverrides | None" = (
        betterproto2.field(
            35, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    communities_leave_community: "_communities__.LeaveCommunity | None" = (
        betterproto2.field(
            36, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    communities_delete_community: "_communities__.DeleteCommunity | None" = (
        betterproto2.field(
            37, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    friends_sync_friends: "_friends__.SyncFriends | None" = betterproto2.field(
        38, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_edit_channel: "_communities__.EditChannel | None" = betterproto2.field(
        39, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_edit_community: "_communities__.EditCommunity | None" = (
        betterproto2.field(
            40, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    auth_get_sessions: "_auth__.GetSessions | None" = betterproto2.field(
        41, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_revoke_sessions: "_auth__.RevokeSessions | None" = betterproto2.field(
        42, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_register_push_subscription: "_settings__.RegisterPushSubscription | None" = betterproto2.field(
        43, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_unregister_push_subscription: "_settings__.UnregisterPushSubscription | None" = betterproto2.field(
        44, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_reset_password: "_auth__.ResetPassword | None" = betterproto2.field(
        45, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_verify_email: "_auth__.VerifyEmail | None" = betterproto2.field(
        46, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    auth_resend_email_verification: "_auth__.ResendEmailVerification | None" = (
        betterproto2.field(
            47, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    users_lookup_username: "_users__.LookupUsername | None" = betterproto2.field(
        48, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_remove_members: "_communities__.RemoveMembers | None" = (
        betterproto2.field(
            49, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    chats_create_chat: "_chats__.CreateChat | None" = betterproto2.field(
        50, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    friends_change_relationship: "_friends__.ChangeRelationship | None" = (
        betterproto2.field(
            51, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    chats_update_chat: "_chats__.UpdateChat | None" = betterproto2.field(
        52, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    chats_remove_chat_member: "_chats__.RemoveChatMember | None" = betterproto2.field(
        53, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    voice_request_room: "_voice__.RequestRoom | None" = betterproto2.field(
        54, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_search: "_messages__.Search | None" = betterproto2.field(
        55, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_get_embed_preview: "_messages__.GetEmbedPreview | None" = (
        betterproto2.field(
            56, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    users_get_profile: "_users__.GetProfile | None" = betterproto2.field(
        57, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_edit_default_permissions: "_communities__.EditDefaultPermissions | None" = betterproto2.field(
        58, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    chats_delete_chat_invite: "_chats__.DeleteChatInvite | None" = betterproto2.field(
        59, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_get_removed_members: "_communities__.GetRemovedMembers | None" = (
        betterproto2.field(
            60, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    chats_list_chat_invites: "_chats__.ListChatInvites | None" = betterproto2.field(
        61, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_report_message: "_messages__.ReportMessage | None" = betterproto2.field(
        62, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    reactions_add_reaction: "_reactions__.AddReaction | None" = betterproto2.field(
        63, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    reactions_remove_reaction: "_reactions__.RemoveReaction | None" = (
        betterproto2.field(
            64, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    messages_forward_message: "_messages__.ForwardMessage | None" = betterproto2.field(
        65, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    stickers_get_saved_stickers: "_stickers__.GetSavedStickers | None" = (
        betterproto2.field(
            66, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    stickers_get_sticker_files: "_stickers__.GetStickerFiles | None" = (
        betterproto2.field(
            67, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    stickers_get_sticker_pack: "_stickers__.GetStickerPack | None" = betterproto2.field(
        68, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    stickers_add_sticker_to_pack: "_stickers__.AddStickerToPack | None" = (
        betterproto2.field(
            69, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    stickers_remove_sticker_from_pack: "_stickers__.RemoveStickerFromPack | None" = (
        betterproto2.field(
            70, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    billing_request_payment_link: "_billing__.RequestPaymentLink | None" = (
        betterproto2.field(
            71, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    billing_cancel_subscription: "_billing__.CancelSubscription | None" = (
        betterproto2.field(
            72, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    settings_change_notification_preferences: "_settings__.ChangeNotificationPreferences | None" = betterproto2.field(
        73, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_edit_profile: "_settings__.EditProfile | None" = betterproto2.field(
        74, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_get_account: "_settings__.GetAccount | None" = betterproto2.field(
        75, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_change_password: "_settings__.ChangePassword | None" = betterproto2.field(
        76, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_change_email: "_settings__.ChangeEmail | None" = betterproto2.field(
        77, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_unban_members: "_communities__.UnbanMembers | None" = (
        betterproto2.field(
            78, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    communities_get_members: "_communities__.GetMembers | None" = betterproto2.field(
        79, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_change_status: "_settings__.ChangeStatus | None" = betterproto2.field(
        80, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_edit_settings: "_communities__.EditSettings | None" = (
        betterproto2.field(
            81, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    billing_get_subscription: "_billing__.GetSubscription | None" = betterproto2.field(
        82, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_setup_totp: "_settings__.SetupTotp | None" = betterproto2.field(
        83, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_request_takeout: "_settings__.RequestTakeout | None" = betterproto2.field(
        84, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    settings_delete_account: "_settings__.DeleteAccount | None" = betterproto2.field(
        85, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_get_unread_mentions: "_messages__.GetUnreadMentions | None" = (
        betterproto2.field(
            86, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    discovery_get_discoverable_communities: "_discovery__.GetDiscoverableCommunities | None" = betterproto2.field(
        87, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    communities_get_room_states: "_communities__.GetRoomStates | None" = (
        betterproto2.field(
            88, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    messages_set_message_pin: "_messages__.SetMessagePin | None" = betterproto2.field(
        89, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    messages_get_pinned_messages: "_messages__.GetPinnedMessages | None" = (
        betterproto2.field(
            90, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )

    settings_edit_user_settings: "_settings__.EditUserSettings | None" = (
        betterproto2.field(
            91, betterproto2.TYPE_MESSAGE, optional=True, group="message"
        )
    )


default_message_pool.register_message(
    "osmium.client.core", "ClientMessage", ClientMessage
)


@dataclass(eq=False, repr=False)
class Entrypoints(betterproto2.Message):
    entrypoints: "list[_types__.Entrypoint]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.core", "Entrypoints", Entrypoints)


@dataclass(eq=False, repr=False)
class Initialize(betterproto2.Message):
    """
    core.Initialize -> core.Initialized
    """

    client_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    device_type: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    device_version: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    app_version: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    no_subscribe: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message("osmium.client.core", "Initialize", Initialize)


@dataclass(eq=False, repr=False)
class Initialized(betterproto2.Message):
    entrypoints: "Entrypoints | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    vapid_public_key: "str | None" = betterproto2.field(
        2, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message("osmium.client.core", "Initialized", Initialized)


@dataclass(eq=False, repr=False)
class RpcError(betterproto2.Message):
    error_code: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    error_message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("osmium.client.core", "RPCError", RpcError)


@dataclass(eq=False, repr=False)
class RpcResult(betterproto2.Message):
    """


    Oneofs:
        - result:
    """

    req_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    trace_id: "str | None" = betterproto2.field(
        37, betterproto2.TYPE_STRING, optional=True
    )

    error: "RpcError | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    sent_message: "_messages__.SentMessage | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    authorization: "_auth__.Authorization | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    communities: "_communities__.Communities | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    channels: "_communities__.Channels | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    messages: "_messages__.Messages | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    relationships: "_friends__.Relationships | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    chats: "_chats__.Chats | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    file_part: "_media__.FilePart | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    created_invite: "_auth__.CreatedInvite | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    member_list: "_communities__.MemberList | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    auth.Invite invite = 12;
    """

    initialized: "Initialized | None" = betterproto2.field(
        14, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    chat: "_chats__.Chat | None" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    community_roles: "_communities__.CommunityRoles | None" = betterproto2.field(
        16, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    channel_override: "_communities__.ChannelOverride | None" = betterproto2.field(
        17, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    channel_overrides: "_communities__.ChannelOverrides | None" = betterproto2.field(
        18, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    sessions: "_auth__.Sessions | None" = betterproto2.field(
        19, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    user_details: "_users__.UserDetails | None" = betterproto2.field(
        20, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    removed_members: "_communities__.RemovedMembers | None" = betterproto2.field(
        21, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    group: "_types__.Group | None" = betterproto2.field(
        22, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    invite_preview: "_auth__.InvitePreview | None" = betterproto2.field(
        23, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    room_info: "_voice__.RoomInfo | None" = betterproto2.field(
        24, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    media_embed: "_media__.MediaEmbed | None" = betterproto2.field(
        25, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    profile: "_users__.Profile | None" = betterproto2.field(
        26, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    invite_list: "_auth__.InviteList | None" = betterproto2.field(
        27, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    saved_stickers: "_stickers__.SavedStickers | None" = betterproto2.field(
        28, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    files: "_media__.Files | None" = betterproto2.field(
        29, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    sticker_pack: "_stickers__.StickerPack | None" = betterproto2.field(
        30, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    payment_link: "_billing__.PaymentLink | None" = betterproto2.field(
        31, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    account: "_settings__.Account | None" = betterproto2.field(
        32, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    members: "_communities__.Members | None" = betterproto2.field(
        33, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    community_settings: "_communities__.CommunitySettings | None" = betterproto2.field(
        34, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    subscription: "_billing__.Subscription | None" = betterproto2.field(
        35, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    totp: "_settings__.Totp | None" = betterproto2.field(
        36, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    unread_mentions: "_messages__.UnreadMentions | None" = betterproto2.field(
        38, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    discovery_communities: "_discovery__.DiscoveryCommunities | None" = (
        betterproto2.field(39, betterproto2.TYPE_MESSAGE, optional=True, group="result")
    )

    room_states: "_communities__.RoomStates | None" = betterproto2.field(
        40, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    user_settings: "_settings__.UserSettings | None" = betterproto2.field(
        41, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )


default_message_pool.register_message("osmium.client.core", "RPCResult", RpcResult)


@dataclass(eq=False, repr=False)
class ServerMessage(betterproto2.Message):
    """


    Oneofs:
        - message:
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    update: "_updates__.Update | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )

    result: "RpcResult | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="message"
    )


default_message_pool.register_message(
    "osmium.client.core", "ServerMessage", ServerMessage
)


from .. import auth as _auth__
from .. import billing as _billing__
from .. import chats as _chats__
from .. import communities as _communities__
from .. import discovery as _discovery__
from .. import friends as _friends__
from .. import media as _media__
from .. import messages as _messages__
from .. import reactions as _reactions__
from .. import settings as _settings__
from .. import stickers as _stickers__
from .. import types as _types__
from .. import updates as _updates__
from .. import users as _users__
from .. import voice as _voice__
