# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: refs.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class ChannelRef(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    channel_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """


default_message_pool.register_message("osmium.client.refs", "ChannelRef", ChannelRef)


@dataclass(eq=False, repr=False)
class ChatRef(betterproto2.Message):
    """
    TODO: This is only meant to be used for input. Current use is ambiguous.

    Oneofs:
        - ref:
    """

    user: "UserRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )

    channel: "ChannelRef | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )

    group: "GroupRef | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )

    self: "RefSelf | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="ref"
    )


default_message_pool.register_message("osmium.client.refs", "ChatRef", ChatRef)


@dataclass(eq=False, repr=False)
class GroupRef(betterproto2.Message):
    group_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Chat>
    """


default_message_pool.register_message("osmium.client.refs", "GroupRef", GroupRef)


@dataclass(eq=False, repr=False)
class RefSelf(betterproto2.Message):
    pass


default_message_pool.register_message("osmium.client.refs", "RefSelf", RefSelf)


@dataclass(eq=False, repr=False)
class StickerPackRef(betterproto2.Message):
    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<StickerPack>

    TODO auth
    """


default_message_pool.register_message(
    "osmium.client.refs", "StickerPackRef", StickerPackRef
)


@dataclass(eq=False, repr=False)
class UserRef(betterproto2.Message):
    user_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """


default_message_pool.register_message("osmium.client.refs", "UserRef", UserRef)
