# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: discovery.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class DiscoveryCommunities(betterproto2.Message):
    listings: "list[DiscoveryCommunityListing]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.discovery", "DiscoveryCommunities", DiscoveryCommunities
)


@dataclass(eq=False, repr=False)
class DiscoveryCommunityListing(betterproto2.Message):
    """
    short description, longer description, categories from user input, icon, name, and identifier
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    photo: "_types__.ChatPhoto | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    invite_code: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    short_description: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)

    long_description: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)

    categories: "list[str]" = betterproto2.field(
        7, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.discovery", "DiscoveryCommunityListing", DiscoveryCommunityListing
)


@dataclass(eq=False, repr=False)
class DiscoveryListingInfo(betterproto2.Message):
    short_description: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    long_description: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    categories: "list[str]" = betterproto2.field(
        4, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.discovery", "DiscoveryListingInfo", DiscoveryListingInfo
)


@dataclass(eq=False, repr=False)
class GetDiscoverableCommunities(betterproto2.Message):
    """
    discovery.getDiscoverableCommunities -> discovery.DiscoveryCommunities
    """

    after: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    pagination
    """

    limit: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "osmium.client.discovery", "GetDiscoverableCommunities", GetDiscoverableCommunities
)


from .. import types as _types__
