# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: billing.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class CancelSubscription(betterproto2.Message):
    """
    billing.cancelSubscription -> billing.CancelSubscription
    """

    pass


default_message_pool.register_message(
    "osmium.client.billing", "CancelSubscription", CancelSubscription
)


@dataclass(eq=False, repr=False)
class GetSubscription(betterproto2.Message):
    """
    billing.getSubscription -> billing.Subscription
    """

    pass


default_message_pool.register_message(
    "osmium.client.billing", "GetSubscription", GetSubscription
)


@dataclass(eq=False, repr=False)
class PaymentLink(betterproto2.Message):
    url: "str | None" = betterproto2.field(1, betterproto2.TYPE_STRING, optional=True)


default_message_pool.register_message(
    "osmium.client.billing", "PaymentLink", PaymentLink
)


@dataclass(eq=False, repr=False)
class RequestPaymentLink(betterproto2.Message):
    """
    billing.requestPaymentLink -> billing.PaymentLink
    """

    redirect_url: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    plan: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    billing_period: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    monthly or yearly
    """


default_message_pool.register_message(
    "osmium.client.billing", "RequestPaymentLink", RequestPaymentLink
)


@dataclass(eq=False, repr=False)
class Subscription(betterproto2.Message):
    active: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    since: "int | None" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, optional=True
    )

    next_renewal_date: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT64, optional=True
    )

    last_card_digits: "str | None" = betterproto2.field(
        4, betterproto2.TYPE_STRING, optional=True
    )

    method: "str | None" = betterproto2.field(
        5, betterproto2.TYPE_STRING, optional=True
    )
    """
    e.g. directdebit, paypal
    """

    end_date: "int | None" = betterproto2.field(
        6, betterproto2.TYPE_UINT64, optional=True
    )


default_message_pool.register_message(
    "osmium.client.billing", "Subscription", Subscription
)
