# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: communities.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class ChannelOverride(betterproto2.Message):
    override: "_types__.ChannelOverride | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "ChannelOverride", ChannelOverride
)


@dataclass(eq=False, repr=False)
class ChannelOverrides(betterproto2.Message):
    overrides: "list[_types__.ChannelOverride]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "ChannelOverrides", ChannelOverrides
)


@dataclass(eq=False, repr=False)
class Channels(betterproto2.Message):
    conversations: "list[_types__.Conversation]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    channels: "list[_types__.Channel]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    messages: "list[_types__.Message]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.communities", "Channels", Channels)


@dataclass(eq=False, repr=False)
class Communities(betterproto2.Message):
    communities: "list[_types__.Community]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    community_user_info: "list[CommunityUserInfo]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    unavailable: "list[int]" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.communities", "Communities", Communities
)


@dataclass(eq=False, repr=False)
class CommunityMemberRoleIds(betterproto2.Message):
    """
    out here cus nested snowflake
    """

    role_ids: "list[int]" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Role>
    """


default_message_pool.register_message(
    "osmium.client.communities", "CommunityMemberRoleIds", CommunityMemberRoleIds
)


@dataclass(eq=False, repr=False)
class CommunityRoles(betterproto2.Message):
    roles: "list[_types__.CommunityRole]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    default_permissions: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)


default_message_pool.register_message(
    "osmium.client.communities", "CommunityRoles", CommunityRoles
)


@dataclass(eq=False, repr=False)
class CommunitySettings(betterproto2.Message):
    system_messages: "CommunitySettingsSystemMessages | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    discovery_listing: "CommunitySettingsDiscoveryListing | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "CommunitySettings", CommunitySettings
)


@dataclass(eq=False, repr=False)
class CommunitySettingsDiscoveryListing(betterproto2.Message):
    listed: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    listing: "_discovery__.DiscoveryListingInfo | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities",
    "CommunitySettings.DiscoveryListing",
    CommunitySettingsDiscoveryListing,
)


@dataclass(eq=False, repr=False)
class CommunitySettingsSystemMessages(betterproto2.Message):
    channel_id: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Channel>
    """

    join_messages: "bool | None" = betterproto2.field(
        2, betterproto2.TYPE_BOOL, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities",
    "CommunitySettings.SystemMessages",
    CommunitySettingsSystemMessages,
)


@dataclass(eq=False, repr=False)
class CommunityUserInfo(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    unread_count: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    unread_mention_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "osmium.client.communities", "CommunityUserInfo", CommunityUserInfo
)


@dataclass(eq=False, repr=False)
class CreateChannel(betterproto2.Message):
    """
    communities.createChannel -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    type: "_types__.ChannelType" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: _types__.ChannelType(0)
    )

    parent_id: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Channel>
    """


default_message_pool.register_message(
    "osmium.client.communities", "CreateChannel", CreateChannel
)


@dataclass(eq=False, repr=False)
class CreateChannelOverride(betterproto2.Message):
    """
    communities.createChannelOverride -> communities.ChannelOverride
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    channel_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """

    role_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Role>
    """

    permissions: "_types__.PermissionOverrides | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "CreateChannelOverride", CreateChannelOverride
)


@dataclass(eq=False, repr=False)
class CreateCommunity(betterproto2.Message):
    """
    community.createCommunity -> ()
    """

    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.communities", "CreateCommunity", CreateCommunity
)


@dataclass(eq=False, repr=False)
class CreateRole(betterproto2.Message):
    """
    communities.createRole -> ()
    """

    community_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    permissions: "int" = betterproto2.field(4, betterproto2.TYPE_FIXED64)

    priority: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)

    color: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)

    separated: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)

    public: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "osmium.client.communities", "CreateRole", CreateRole
)


@dataclass(eq=False, repr=False)
class DeleteChannel(betterproto2.Message):
    """
    communities.deleteChannel -> ()
    """

    channel: "_refs__.ChannelRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "DeleteChannel", DeleteChannel
)


@dataclass(eq=False, repr=False)
class DeleteChannelOverride(betterproto2.Message):
    """
    communities.deleteChannelOverride -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    channel_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """

    role_id: "int" = betterproto2.field(3, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Role>
    """


default_message_pool.register_message(
    "osmium.client.communities", "DeleteChannelOverride", DeleteChannelOverride
)


@dataclass(eq=False, repr=False)
class DeleteCommunity(betterproto2.Message):
    """
    communities.deleteCommunity -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.communities", "DeleteCommunity", DeleteCommunity
)


@dataclass(eq=False, repr=False)
class DeleteRole(betterproto2.Message):
    """
    communities.deleteRole -> ()
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Role>
    """

    community_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.communities", "DeleteRole", DeleteRole
)


@dataclass(eq=False, repr=False)
class EditChannel(betterproto2.Message):
    """
    communities.editChannel -> ()
    """

    channel: "_refs__.ChannelRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    name: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True)

    position: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT32, optional=True
    )

    parent_id: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Channel>
    """

    explicit: "bool | None" = betterproto2.field(
        5, betterproto2.TYPE_BOOL, optional=True
    )

    highlighted_msg_id: "EditChannelHighlightedMessage | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    None to not modify, 0 to modify to None, >0 to modify to Some(msg_id)
    """


default_message_pool.register_message(
    "osmium.client.communities", "EditChannel", EditChannel
)


@dataclass(eq=False, repr=False)
class EditChannelHighlightedMessage(betterproto2.Message):
    highlighted_msg_id: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.communities",
    "EditChannel.HighlightedMessage",
    EditChannelHighlightedMessage,
)


@dataclass(eq=False, repr=False)
class EditCommunity(betterproto2.Message):
    """
    communities.editCommunity -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    name: "str | None" = betterproto2.field(2, betterproto2.TYPE_STRING, optional=True)

    username: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "EditCommunity", EditCommunity
)


@dataclass(eq=False, repr=False)
class EditDefaultPermissions(betterproto2.Message):
    """
    Edits default permissions given to all members
    communities.editDefaultPermissions -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    permissions: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)


default_message_pool.register_message(
    "osmium.client.communities", "EditDefaultPermissions", EditDefaultPermissions
)


@dataclass(eq=False, repr=False)
class EditMember(betterproto2.Message):
    """
    communities.editMember -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    member_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    nickname: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )

    role_ids: "CommunityMemberRoleIds | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "EditMember", EditMember
)


@dataclass(eq=False, repr=False)
class EditPhoto(betterproto2.Message):
    """
    communities.editPhoto -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    file: "_media__.UploadedFileRef | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "EditPhoto", EditPhoto
)


@dataclass(eq=False, repr=False)
class EditRole(betterproto2.Message):
    """
    communities.editRole -> ()
    """

    id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Role>
    """

    community_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    permissions: "int" = betterproto2.field(4, betterproto2.TYPE_FIXED64)

    priority: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)

    color: "int" = betterproto2.field(6, betterproto2.TYPE_UINT32)

    separated: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)

    public: "bool" = betterproto2.field(8, betterproto2.TYPE_BOOL)


default_message_pool.register_message("osmium.client.communities", "EditRole", EditRole)


@dataclass(eq=False, repr=False)
class EditSettings(betterproto2.Message):
    """
    communities.editSettings -> communities.CommunitySettings
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    settings: "CommunitySettings | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "EditSettings", EditSettings
)


@dataclass(eq=False, repr=False)
class GetChannelMembers(betterproto2.Message):
    """
    communities.GetChannelMembers -> communities.MemberList
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    channel_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """


default_message_pool.register_message(
    "osmium.client.communities", "GetChannelMembers", GetChannelMembers
)


@dataclass(eq=False, repr=False)
class GetChannelOverrides(betterproto2.Message):
    """
    communities.getChannelOverrides -> communities.ChannelOverrides
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    channel_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """


default_message_pool.register_message(
    "osmium.client.communities", "GetChannelOverrides", GetChannelOverrides
)


@dataclass(eq=False, repr=False)
class GetChannels(betterproto2.Message):
    """
    communities.getChannels -> communities.Channels
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.communities", "GetChannels", GetChannels
)


@dataclass(eq=False, repr=False)
class GetCommunities(betterproto2.Message):
    """
    communities.getCommunities -> communities.Communities
    """

    pass


default_message_pool.register_message(
    "osmium.client.communities", "GetCommunities", GetCommunities
)


@dataclass(eq=False, repr=False)
class GetMembers(betterproto2.Message):
    """
    communities.getMembers -> communities.Members
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    member_ids: "list[int]" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<User>
    """


default_message_pool.register_message(
    "osmium.client.communities", "GetMembers", GetMembers
)


@dataclass(eq=False, repr=False)
class GetRemovedMembers(betterproto2.Message):
    """
    communities.getRemovedMembers -> communities.RemovedMembers
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.communities", "GetRemovedMembers", GetRemovedMembers
)


@dataclass(eq=False, repr=False)
class GetRoles(betterproto2.Message):
    """
    Fetches roles in the community that the user is allowed to see.
    Meant to be admin only, currently not enforced until Member List v2

    communities.getRoles -> communities.CommunityRoles
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message("osmium.client.communities", "GetRoles", GetRoles)


@dataclass(eq=False, repr=False)
class GetRoomStates(betterproto2.Message):
    """
    communities.getRoomStates -> communities.RoomStates
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.communities", "GetRoomStates", GetRoomStates
)


@dataclass(eq=False, repr=False)
class LeaveCommunity(betterproto2.Message):
    """
    communities.leaveCommunity -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.communities", "LeaveCommunity", LeaveCommunity
)


@dataclass(eq=False, repr=False)
class MemberList(betterproto2.Message):
    entries: "list[_updates__.MemberListEntry]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "MemberList", MemberList
)


@dataclass(eq=False, repr=False)
class Members(betterproto2.Message):
    members: "list[_types__.CommunityMember]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    users: "list[_types__.User]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.communities", "Members", Members)


@dataclass(eq=False, repr=False)
class RemovedMembers(betterproto2.Message):
    members: "list[RemovedMembersRemovedMember]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "RemovedMembers", RemovedMembers
)


@dataclass(eq=False, repr=False)
class RemovedMembersRemovedMember(betterproto2.Message):
    user_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    user: "_types__.User | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    until: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, optional=True
    )

    reason: "str | None" = betterproto2.field(
        4, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities",
    "RemovedMembers.RemovedMember",
    RemovedMembersRemovedMember,
)


@dataclass(eq=False, repr=False)
class RemoveMembers(betterproto2.Message):
    """
    Removes a list of members from the community

    communities.removeMembers -> RemovedMembers
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    member_ids: "list[int]" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<User>
    """

    until: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    Unix timestamp. Zero value results in a permanent ban.
    """

    delete_messages_since: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    Unix timestamp.
    """

    reason: "str | None" = betterproto2.field(
        5, betterproto2.TYPE_STRING, optional=True
    )
    """
    Optional reason for removal/ban
    """


default_message_pool.register_message(
    "osmium.client.communities", "RemoveMembers", RemoveMembers
)


@dataclass(eq=False, repr=False)
class RoomStates(betterproto2.Message):
    room_states: "list[RoomStatesRoomState]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "RoomStates", RoomStates
)


@dataclass(eq=False, repr=False)
class RoomStatesRoomState(betterproto2.Message):
    channel_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """

    state: "_voice__.RoomState | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.communities", "RoomStates.RoomState", RoomStatesRoomState
)


@dataclass(eq=False, repr=False)
class UnbanMembers(betterproto2.Message):
    """
    communities.unbanMembers -> ()
    """

    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    member_ids: "list[int]" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<User>
    """


default_message_pool.register_message(
    "osmium.client.communities", "UnbanMembers", UnbanMembers
)


from .. import discovery as _discovery__
from .. import media as _media__
from .. import refs as _refs__
from .. import types as _types__
from .. import updates as _updates__
from .. import voice as _voice__
