"""Post-process the generated betterproto2 sources.

betterproto2 derives class names straight from the proto message names and
offers no prefix/suffix option, so instead of touching the generated class
definitions we:

1. Write ``osmium_protos/__init__.py``: re-export ``unwrap``/``wrap`` plus a flat
   alias of every message/enum under a ``PB_`` prefix (the surface consumers
   import from).
2. Clear the ``__all__`` of every generated package so linters / autocomplete
   stop suggesting the unaliased names.

Names that are unique across packages become ``PB_<Name>``. The handful that
collide across packages are disambiguated by folding the package name in, e.g.
``PB_ChatsUpdateChat`` and ``PB_UpdatesUpdateChat``.

Discovery is done by introspecting the actual classes (not ``__all__``), so the
script is idempotent even after step 2 has emptied every ``__all__``.
"""

from __future__ import annotations

import collections
import importlib
import inspect
import pkgutil
import re
import sys
from pathlib import Path

import betterproto2

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import osmium_protos.osmium.client as client_pkg  # noqa: E402

INIT_MODULE = REPO_ROOT / "osmium_protos" / "__init__.py"
CLIENT_PREFIX = "osmium_protos.osmium.client"
ALL_RE = re.compile(r"__all__ = \([^)]*\)")


def public_names(module) -> tuple[str, ...]:
    """Message/enum classes defined in this module (ignores imported aliases)."""
    names = [
        name
        for name, obj in vars(module).items()
        if inspect.isclass(obj)
        and issubclass(obj, (betterproto2.Message, betterproto2.Enum))
        and obj.__module__ == module.__name__
    ]
    return tuple(sorted(names))


def main() -> None:
    modules = {
        m.name: importlib.import_module(f"{CLIENT_PREFIX}.{m.name}")
        for m in sorted(pkgutil.iter_modules(client_pkg.__path__), key=lambda m: m.name)
    }

    names_by_package = {pkg: public_names(mod) for pkg, mod in modules.items()}

    packages_by_name: dict[str, list[str]] = collections.defaultdict(list)
    for pkg, names in names_by_package.items():
        for name in names:
            packages_by_name[name].append(pkg)

    def alias_for(package: str, name: str) -> str:
        if len(packages_by_name[name]) == 1:
            return f"PB_{name}"
        # Collision: disambiguate with the CamelCased package name.
        return f"PB_{package.capitalize()}{name}"

    # --- 1. Write osmium_protos/__init__.py --------------------------------
    lines: list[str] = [
        "# Generated by scripts/gen_pb_aliases.py. DO NOT EDIT!",
        '"""``unwrap``/``wrap`` plus a flat ``PB_``-prefixed alias of every proto message and enum."""',
        "",
        "from osmium_protos.unwrap import unwrap",
        "from osmium_protos.wrap import wrap",
        "",
    ]
    all_aliases: list[str] = []
    for package, names in names_by_package.items():
        if not names:
            continue
        lines.append(f"from {CLIENT_PREFIX}.{package} import (")
        for name in names:
            alias = alias_for(package, name)
            all_aliases.append(alias)
            lines.append(f"    {name} as {alias},")
        lines.append(")")

    lines.append("")
    lines.append("__all__ = (")
    lines.append('    "unwrap",')
    lines.append('    "wrap",')
    for alias in sorted(all_aliases):
        lines.append(f'    "{alias}",')
    lines.append(")")
    lines.append("")
    INIT_MODULE.write_text("\n".join(lines))
    print(f"Wrote {len(all_aliases)} aliases to {INIT_MODULE}")

    # --- 2. Clear __all__ in every generated package -----------------------
    cleared = 0
    for mod in modules.values():
        if not mod.__file__:
            continue
        path = Path(mod.__file__)
        text = path.read_text()
        new_text, n = ALL_RE.subn("__all__ = ()", text, count=1)
        if n:
            path.write_text(new_text)
            cleared += 1
    print(f"Cleared __all__ in {cleared} generated packages")


if __name__ == "__main__":
    main()
