# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class DeleteMessage(betterproto2.Message):
    """
    messages.deleteMessage -> ()
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_ids: "list[int]" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.messages", "DeleteMessage", DeleteMessage
)


@dataclass(eq=False, repr=False)
class EditMessage(betterproto2.Message):
    """
    messages.editMessage -> ()
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    message: "str | None" = betterproto2.field(
        3, betterproto2.TYPE_STRING, optional=True
    )

    remove_media: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)

    media: "list[_media__.MediaRef]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    Replaces media
    """

    entities: "list[_types__.MessageEntity]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    Replaces entities if not empty or if message is set.
    """


default_message_pool.register_message(
    "osmium.client.messages", "EditMessage", EditMessage
)


@dataclass(eq=False, repr=False)
class ForwardMessage(betterproto2.Message):
    """
    messages.forwardMessage -> ()
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    from_: "_refs__.ChatRef | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_ids: "list[int]" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.messages", "ForwardMessage", ForwardMessage
)


@dataclass(eq=False, repr=False)
class GetEmbedPreview(betterproto2.Message):
    """
    messages.getEmbedPreview -> media.MediaEmbed
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    entities: "list[_types__.MessageEntity]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.messages", "GetEmbedPreview", GetEmbedPreview
)


@dataclass(eq=False, repr=False)
class GetHistory(betterproto2.Message):
    """
    messages.getHistory -> messages.Messages

    Oneofs:
        - offset:
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    limit: "int | None" = betterproto2.field(2, betterproto2.TYPE_UINT32, optional=True)
    """
    Limit the number of messages to return. Defaults to 50, split when using
    around.
    """

    since: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, optional=True, group="offset"
    )
    """
    @snowflake<Message>
    """

    before: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, optional=True, group="offset"
    )
    """
    @snowflake<Message>
    """

    around: "int | None" = betterproto2.field(
        5, betterproto2.TYPE_FIXED64, optional=True, group="offset"
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.messages", "GetHistory", GetHistory
)


@dataclass(eq=False, repr=False)
class GetPinnedMessages(betterproto2.Message):
    """
    messages.getPinnedMessages -> messages.Messages
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.messages", "GetPinnedMessages", GetPinnedMessages
)


@dataclass(eq=False, repr=False)
class GetUnreadMentions(betterproto2.Message):
    """
    messages.getUnreadMentions -> messages.UnreadMentions
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.messages", "GetUnreadMentions", GetUnreadMentions
)


@dataclass(eq=False, repr=False)
class Messages(betterproto2.Message):
    messages: "list[_types__.Message]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    users: "list[_types__.User]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    members: "list[_types__.CommunityMember]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    reactions: "list[_reactions__.MessageReactions]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("osmium.client.messages", "Messages", Messages)


@dataclass(eq=False, repr=False)
class ReportMessage(betterproto2.Message):
    """
    messages.reportMessage -> ()
    """

    message_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    reason: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "osmium.client.messages", "ReportMessage", ReportMessage
)


@dataclass(eq=False, repr=False)
class Search(betterproto2.Message):
    """
    messages.search -> messages.Messages

    Oneofs:
        - offset:
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    query: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    scoped: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    A scoped query searches only the specific channel, rather than the entire parent. For global search, see messages.searchAll
    """

    since: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_FIXED64, optional=True, group="offset"
    )
    """
    @snowflake<Message>
    """

    before: "int | None" = betterproto2.field(
        5, betterproto2.TYPE_FIXED64, optional=True, group="offset"
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message("osmium.client.messages", "Search", Search)


@dataclass(eq=False, repr=False)
class SendMessage(betterproto2.Message):
    """
    messages.sendMessage -> messages.SentMessage
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    reply_to: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Message>
    """

    media: "list[_media__.MediaRef]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )

    entities: "list[_types__.MessageEntity]" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.messages", "SendMessage", SendMessage
)


@dataclass(eq=False, repr=False)
class SentMessage(betterproto2.Message):
    message_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.messages", "SentMessage", SentMessage
)


@dataclass(eq=False, repr=False)
class SetMessagePin(betterproto2.Message):
    """
    messages.setMessagePin -> ()
    """

    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    pin: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "osmium.client.messages", "SetMessagePin", SetMessagePin
)


@dataclass(eq=False, repr=False)
class UnreadMentions(betterproto2.Message):
    message_ids: "list[int]" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.messages", "UnreadMentions", UnreadMentions
)


from .. import media as _media__
from .. import reactions as _reactions__
from .. import refs as _refs__
from .. import types as _types__
