# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: updates.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ()

from dataclasses import dataclass

import betterproto2

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class MemberListEntry(betterproto2.Message):
    """


    Oneofs:
        - entry:
    """

    user: "MemberListEntryUser | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="entry"
    )

    divider: "MemberListEntryDivider | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="entry"
    )


default_message_pool.register_message(
    "osmium.client.updates", "MemberListEntry", MemberListEntry
)


@dataclass(eq=False, repr=False)
class MemberListEntryDivider(betterproto2.Message):
    """


    Oneofs:
        - inner:
    """

    online: "bool | None" = betterproto2.field(
        1, betterproto2.TYPE_BOOL, optional=True, group="inner"
    )

    role_id: "int | None" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, optional=True, group="inner"
    )
    """
    @snowflake<Role>
    """

    member_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "osmium.client.updates", "MemberListEntryDivider", MemberListEntryDivider
)


@dataclass(eq=False, repr=False)
class MemberListEntryUser(betterproto2.Message):
    user: "_types__.User | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    nickname: "str | None" = betterproto2.field(
        2, betterproto2.TYPE_STRING, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "MemberListEntryUser", MemberListEntryUser
)


@dataclass(eq=False, repr=False)
class Update(betterproto2.Message):
    """


    Oneofs:
        - update:
    """

    message_created: "UpdateMessageCreated | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    channel: "UpdateChannel | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    message_deleted: "UpdateMessageDeleted | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    user_status: "UpdateUserStatus | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    user: "UpdateUser | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    community: "UpdateCommunity | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    channel_deleted: "UpdateChannelDeleted | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    message: "UpdateMessage | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    chat_typing: "UpdateChatTyping | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    community_member: "UpdateCommunityMember | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    community_deleted: "UpdateCommunityDeleted | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    conversation_permissions: "UpdateConversationPermissions | None" = (
        betterproto2.field(12, betterproto2.TYPE_MESSAGE, optional=True, group="update")
    )

    chat: "UpdateChat | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    session_deleted: "UpdateSessionDeleted | None" = betterproto2.field(
        14, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    community_unavailable: "UpdateCommunityUnavailable | None" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    member_list: "UpdateMemberList | None" = betterproto2.field(
        16, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    community_member_deleted: "UpdateCommunityMemberDeleted | None" = (
        betterproto2.field(17, betterproto2.TYPE_MESSAGE, optional=True, group="update")
    )

    update_user_relationship: "UpdateUserRelationship | None" = betterproto2.field(
        18, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    update_user_relationship_deleted: "UpdateUserRelationshipDeleted | None" = (
        betterproto2.field(19, betterproto2.TYPE_MESSAGE, optional=True, group="update")
    )

    group: "UpdateGroup | None" = betterproto2.field(
        20, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    room_state: "_voice__.UpdateRoomState | None" = betterproto2.field(
        21, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    room_participant: "_voice__.UpdateRoomParticipant | None" = betterproto2.field(
        22, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    message_reactions: "UpdateMessageReactions | None" = betterproto2.field(
        23, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    conversation_last_read: "UpdateConversationLastRead | None" = betterproto2.field(
        24, betterproto2.TYPE_MESSAGE, optional=True, group="update"
    )

    community_member_created: "UpdateCommunityMemberCreated | None" = (
        betterproto2.field(25, betterproto2.TYPE_MESSAGE, optional=True, group="update")
    )


default_message_pool.register_message("osmium.client.updates", "Update", Update)


@dataclass(eq=False, repr=False)
class UpdateChannel(betterproto2.Message):
    channel: "_types__.Channel | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateChannel", UpdateChannel
)


@dataclass(eq=False, repr=False)
class UpdateChannelDeleted(betterproto2.Message):
    channel: "_refs__.ChannelRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateChannelDeleted", UpdateChannelDeleted
)


@dataclass(eq=False, repr=False)
class UpdateChat(betterproto2.Message):
    chat: "_chats__.Chat | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.updates", "UpdateChat", UpdateChat)


@dataclass(eq=False, repr=False)
class UpdateChatTyping(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    user_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    typing: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    action: "_chats__.TypingAction | None" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateChatTyping", UpdateChatTyping
)


@dataclass(eq=False, repr=False)
class UpdateCommunity(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    community: "_types__.Community | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateCommunity", UpdateCommunity
)


@dataclass(eq=False, repr=False)
class UpdateCommunityDeleted(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.updates", "UpdateCommunityDeleted", UpdateCommunityDeleted
)


@dataclass(eq=False, repr=False)
class UpdateCommunityMember(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    member_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    member: "_types__.CommunityMember | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateCommunityMember", UpdateCommunityMember
)


@dataclass(eq=False, repr=False)
class UpdateCommunityMemberCreated(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    member_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    member: "_types__.CommunityMember | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    user: "_types__.User | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates",
    "UpdateCommunityMemberCreated",
    UpdateCommunityMemberCreated,
)


@dataclass(eq=False, repr=False)
class UpdateCommunityMemberDeleted(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """

    member_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """


default_message_pool.register_message(
    "osmium.client.updates",
    "UpdateCommunityMemberDeleted",
    UpdateCommunityMemberDeleted,
)


@dataclass(eq=False, repr=False)
class UpdateCommunityUnavailable(betterproto2.Message):
    community_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Community>
    """


default_message_pool.register_message(
    "osmium.client.updates", "UpdateCommunityUnavailable", UpdateCommunityUnavailable
)


@dataclass(eq=False, repr=False)
class UpdateConversationLastRead(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    last_read_message_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Message>
    """

    unread_count: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT32, optional=True
    )

    unread_mentions_count: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_UINT32, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateConversationLastRead", UpdateConversationLastRead
)


@dataclass(eq=False, repr=False)
class UpdateConversationPermissions(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    permissions: "_types__.PermissionOverrides | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates",
    "UpdateConversationPermissions",
    UpdateConversationPermissions,
)


@dataclass(eq=False, repr=False)
class UpdateGroup(betterproto2.Message):
    group: "_types__.Group | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    users: "list[_types__.User]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateGroup", UpdateGroup
)


@dataclass(eq=False, repr=False)
class UpdateMemberList(betterproto2.Message):
    community_id: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_FIXED64, optional=True
    )
    """
    @snowflake<Community>
    """

    channel_id: "int" = betterproto2.field(2, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Channel>
    """

    entries: "list[MemberListEntry]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateMemberList", UpdateMemberList
)


@dataclass(eq=False, repr=False)
class UpdateMessage(betterproto2.Message):
    message: "_types__.Message | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateMessage", UpdateMessage
)


@dataclass(eq=False, repr=False)
class UpdateMessageCreated(betterproto2.Message):
    message: "_types__.Message | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    channel_unread_count: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    author: "_types__.User | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    The author of the message. Mostly used in communities. Do not assume this
    is always present.
    """


default_message_pool.register_message(
    "osmium.client.updates", "UpdateMessageCreated", UpdateMessageCreated
)


@dataclass(eq=False, repr=False)
class UpdateMessageDeleted(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    message_ids: "list[int]" = betterproto2.field(
        2, betterproto2.TYPE_FIXED64, repeated=True
    )
    """
    @snowflake<Message>
    """


default_message_pool.register_message(
    "osmium.client.updates", "UpdateMessageDeleted", UpdateMessageDeleted
)


@dataclass(eq=False, repr=False)
class UpdateMessageReactions(betterproto2.Message):
    chat_ref: "_refs__.ChatRef | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    reactions: "_reactions__.MessageReactions | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateMessageReactions", UpdateMessageReactions
)


@dataclass(eq=False, repr=False)
class UpdateSessionDeleted(betterproto2.Message):
    session_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<Session>
    """


default_message_pool.register_message(
    "osmium.client.updates", "UpdateSessionDeleted", UpdateSessionDeleted
)


@dataclass(eq=False, repr=False)
class UpdateUser(betterproto2.Message):
    user_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    user: "_types__.User | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("osmium.client.updates", "UpdateUser", UpdateUser)


@dataclass(eq=False, repr=False)
class UpdateUserRelationship(betterproto2.Message):
    relationship: "_types__.Relationship | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateUserRelationship", UpdateUserRelationship
)


@dataclass(eq=False, repr=False)
class UpdateUserRelationshipDeleted(betterproto2.Message):
    other_user_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """


default_message_pool.register_message(
    "osmium.client.updates",
    "UpdateUserRelationshipDeleted",
    UpdateUserRelationshipDeleted,
)


@dataclass(eq=False, repr=False)
class UpdateUserStatus(betterproto2.Message):
    user_id: "int" = betterproto2.field(1, betterproto2.TYPE_FIXED64)
    """
    @snowflake<User>
    """

    status: "_types__.UserStatus | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "osmium.client.updates", "UpdateUserStatus", UpdateUserStatus
)


from .. import chats as _chats__
from .. import reactions as _reactions__
from .. import refs as _refs__
from .. import types as _types__
from .. import voice as _voice__
